// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicHoarder.Api.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicHoarder.Api.Persistence.Migrations
{
    [DbContext(typeof(MusicHoarderDbContext))]
    [Migration("20260520220020_AddIngestRunHistory")]
    partial class AddIngestRunHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicHoarder.Api.Auth.MagicLinkToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedFromIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequestedUserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ConsumedAtUtc", "ExpiresAtUtc");

                    b.ToTable("MagicLinkTokens");
                });

            modelBuilder.Entity("MusicHoarder.Api.Auth.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("MusicHoarder.Api.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c0f1e3d-7b6a-4d2e-9c8f-0a1b2c3d4e5f"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Owner",
                            Email = "owner@unconfigured.local",
                            EmailNormalized = "OWNER@UNCONFIGURED.LOCAL",
                            IsDisabled = false,
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-4d6e-9f80-112233445566"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Demo",
                            Email = "demo@unconfigured.local",
                            EmailNormalized = "DEMO@UNCONFIGURED.LOCAL",
                            IsDisabled = false,
                            Role = 1
                        });
                });

            modelBuilder.Entity("MusicHoarder.Api.Persistence.IngestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogTailJson")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("ThroughputPerSec")
                        .HasColumnType("double precision");

                    b.Property<int>("TracksCopied")
                        .HasColumnType("integer");

                    b.Property<int>("TracksDiscovered")
                        .HasColumnType("integer");

                    b.Property<int>("TracksEnriched")
                        .HasColumnType("integer");

                    b.Property<int>("TracksFailed")
                        .HasColumnType("integer");

                    b.Property<int>("TracksFingerprinted")
                        .HasColumnType("integer");

                    b.Property<int>("TracksProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("TracksReview")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "StartedAtUtc");

                    b.ToTable("IngestRuns");
                });

            modelBuilder.Entity("MusicHoarder.Api.Persistence.RuntimeSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AcoustIdScoreThreshold")
                        .HasColumnType("double precision");

                    b.Property<bool?>("EnableAcoustIdProvider")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EnableMusicBrainzWebProvider")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EnableSpotifyApiProvider")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EnableTrackerProvider")
                        .HasColumnType("boolean");

                    b.Property<int?>("EnrichmentWorkerConcurrency")
                        .HasColumnType("integer");

                    b.Property<int?>("LibraryBuilderWorkerConcurrency")
                        .HasColumnType("integer");

                    b.Property<double?>("SpotifyApiMatchedThreshold")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RuntimeSettings");
                });

            modelBuilder.Entity("MusicHoarder.Api.Persistence.SongMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcoustIdTrackId")
                        .HasColumnType("text");

                    b.Property<string>("Album")
                        .HasColumnType("text");

                    b.Property<string>("AlbumArtist")
                        .HasColumnType("text");

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<int?>("Bitrate")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationPath")
                        .HasColumnType("text");

                    b.Property<int?>("DuplicateOfId")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EnrichedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnrichmentError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EnrichmentLastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnrichmentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("text");

                    b.Property<DateTime>("IndexedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsInstrumental")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnreleased")
                        .HasColumnType("boolean");

                    b.Property<string>("Isrc")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LibraryBuildError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LibraryBuildLastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LibraryBuildStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LibraryBuiltAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LrclibId")
                        .HasColumnType("text");

                    b.Property<int>("LyricsStatus")
                        .HasColumnType("integer");

                    b.Property<double?>("MatchConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("MatchWarnings")
                        .HasColumnType("text");

                    b.Property<string>("MatchedBy")
                        .HasColumnType("text");

                    b.Property<string>("MusicBrainzId")
                        .HasColumnType("text");

                    b.Property<string>("MusicBrainzReleaseId")
                        .HasColumnType("text");

                    b.Property<string>("OriginalAlbum")
                        .HasColumnType("text");

                    b.Property<string>("OriginalAlbumArtist")
                        .HasColumnType("text");

                    b.Property<string>("OriginalArtist")
                        .HasColumnType("text");

                    b.Property<string>("OriginalIsrc")
                        .HasColumnType("text");

                    b.Property<bool>("OriginalMetadataCaptured")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OriginalMetadataCapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalMusicBrainzId")
                        .HasColumnType("text");

                    b.Property<string>("OriginalSpotifyId")
                        .HasColumnType("text");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text");

                    b.Property<int?>("OriginalTrackNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("OriginalYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlainLyrics")
                        .HasColumnType("text");

                    b.Property<string>("PreviousDestinationPath")
                        .HasColumnType("text");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("text");

                    b.Property<string>("SyncedLyrics")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinationPath");

                    b.HasIndex("DuplicateOfId");

                    b.HasIndex("Fingerprint");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Fingerprint"), "hash");

                    b.HasIndex("DeletedAtUtc", "IsDuplicate");

                    b.HasIndex("DeletedAtUtc", "LastModifiedUtc");

                    b.HasIndex("OwnerUserId", "DeletedAtUtc");

                    b.HasIndex("OwnerUserId", "SourcePath")
                        .IsUnique();

                    b.HasIndex("DeletedAtUtc", "EnrichmentStatus", "Id");

                    b.HasIndex("DeletedAtUtc", "EnrichmentStatus", "LibraryBuildStatus", "Id");

                    b.HasIndex("DeletedAtUtc", "AlbumArtist", "Album", "Year", "Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("MusicHoarder.Api.Persistence.SongProviderAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("MatchedDataJson")
                        .HasColumnType("text");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RetryAfterUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SongId", "Provider")
                        .IsUnique();

                    b.HasIndex("Status", "RetryAfterUtc");

                    b.ToTable("SongProviderAttempts");
                });

            modelBuilder.Entity("MusicHoarder.Api.Persistence.SpotifySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<int?>("SpotifyLikedMatchInLibrary")
                        .HasColumnType("integer");

                    b.Property<int?>("SpotifyLikedMatchNotInLibrary")
                        .HasColumnType("integer");

                    b.Property<int?>("SpotifyLikedMatchPossible")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SpotifyLikedMatchStatsUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SpotifyLikedMatchTotal")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("SpotifySettings");
                });

            modelBuilder.Entity("MusicHoarder.Api.Persistence.SpotifyTrackLibraryMatch", b =>
                {
                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpotifyTrackId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("MatchConfidence")
                        .HasColumnType("double precision");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("integer");

                    b.Property<string>("MatchedArtist")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MatchedEnrichmentStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("MatchedSongId")
                        .HasColumnType("integer");

                    b.Property<string>("MatchedTitle")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("SpotifyAddedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpotifyAlbum")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SpotifyArtist")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("SpotifyDurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("SpotifyTitle")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OwnerUserId", "SpotifyTrackId");

                    b.HasIndex("MatchStatus");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("SpotifyTrackLibraryMatches");
                });

            modelBuilder.Entity("MusicHoarder.Api.Auth.MagicLinkToken", b =>
                {
                    b.HasOne("MusicHoarder.Api.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicHoarder.Api.Auth.Session", b =>
                {
                    b.HasOne("MusicHoarder.Api.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicHoarder.Api.Persistence.SongMetadata", b =>
                {
                    b.HasOne("MusicHoarder.Api.Persistence.SongMetadata", "DuplicateOf")
                        .WithMany()
                        .HasForeignKey("DuplicateOfId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DuplicateOf");
                });

            modelBuilder.Entity("MusicHoarder.Api.Persistence.SongProviderAttempt", b =>
                {
                    b.HasOne("MusicHoarder.Api.Persistence.SongMetadata", "Song")
                        .WithMany("ProviderAttempts")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MusicHoarder.Api.Persistence.SongMetadata", b =>
                {
                    b.Navigation("ProviderAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
