// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicHoarder.Api.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicHoarder.Api.Persistence.Migrations
{
    [DbContext(typeof(MusicHoarderDbContext))]
    [Migration("20260319065802_AddDuplicateDetectionFields")]
    partial class AddDuplicateDetectionFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicHoarder.Api.Persistence.SongMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .HasColumnType("text");

                    b.Property<string>("AlbumArtist")
                        .HasColumnType("text");

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<int?>("Bitrate")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationPath")
                        .HasColumnType("text");

                    b.Property<int?>("DuplicateOfId")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EnrichedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnrichmentError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EnrichmentLastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnrichmentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("text");

                    b.Property<DateTime>("IndexedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsInstrumental")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnreleased")
                        .HasColumnType("boolean");

                    b.Property<string>("Isrc")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LibraryBuildError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LibraryBuildLastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LibraryBuildStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LibraryBuiltAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LyricsStatus")
                        .HasColumnType("integer");

                    b.Property<double?>("MatchConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("MatchWarnings")
                        .HasColumnType("text");

                    b.Property<string>("MatchedBy")
                        .HasColumnType("text");

                    b.Property<string>("MusicBrainzId")
                        .HasColumnType("text");

                    b.Property<string>("OriginalAlbum")
                        .HasColumnType("text");

                    b.Property<string>("OriginalAlbumArtist")
                        .HasColumnType("text");

                    b.Property<string>("OriginalArtist")
                        .HasColumnType("text");

                    b.Property<string>("OriginalIsrc")
                        .HasColumnType("text");

                    b.Property<bool>("OriginalMetadataCaptured")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OriginalMetadataCapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalMusicBrainzId")
                        .HasColumnType("text");

                    b.Property<string>("OriginalSpotifyId")
                        .HasColumnType("text");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("text");

                    b.Property<int?>("OriginalTrackNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("OriginalYear")
                        .HasColumnType("integer");

                    b.Property<string>("PlainLyrics")
                        .HasColumnType("text");

                    b.Property<string>("PreviousDestinationPath")
                        .HasColumnType("text");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("text");

                    b.Property<string>("SyncedLyrics")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinationPath");

                    b.HasIndex("DuplicateOfId");

                    b.HasIndex("Fingerprint");

                    b.HasIndex("SourcePath")
                        .IsUnique();

                    b.HasIndex("DeletedAtUtc", "IsDuplicate");

                    b.HasIndex("DeletedAtUtc", "LastModifiedUtc");

                    b.HasIndex("DeletedAtUtc", "EnrichmentStatus", "Id");

                    b.HasIndex("DeletedAtUtc", "EnrichmentStatus", "LibraryBuildStatus", "Id");

                    b.HasIndex("DeletedAtUtc", "AlbumArtist", "Album", "Year", "Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("MusicHoarder.Api.Persistence.SongMetadata", b =>
                {
                    b.HasOne("MusicHoarder.Api.Persistence.SongMetadata", "DuplicateOf")
                        .WithMany()
                        .HasForeignKey("DuplicateOfId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DuplicateOf");
                });
#pragma warning restore 612, 618
        }
    }
}
