import type { FileItem, ImportJob, TrackImport, Artist, DiscographyAlbum, SpotifyPlaylist, SpotifyTrack } from "./types"

const SOURCE_ROOT = "/Volumes/music"

export const mockFileSystem: FileItem[] = [
  {
    id: "root",
    name: "music",
    type: "folder",
    path: SOURCE_ROOT,
    parentId: null,
    children: [
      // Messy: CD Rips with generic filenames
      {
        id: "folder-cdrips",
        name: "CD Rips",
        type: "folder",
        path: `${SOURCE_ROOT}/CD Rips`,
        parentId: "root",
        children: [
          {
            id: "folder-disc1",
            name: "Disc1",
            type: "folder",
            path: `${SOURCE_ROOT}/CD Rips/Disc1`,
            parentId: "folder-cdrips",
            children: [
              {
                id: "track-cd1",
                name: "01 - unknown.wav",
                type: "audio",
                path: `${SOURCE_ROOT}/CD Rips/Disc1/01 - unknown.wav`,
                parentId: "folder-disc1",
                metadata: {
                  title: "Track 01",
                  artist: "Unknown Artist",
                  album: "Disc1",
                  year: 0,
                  genre: "Unknown",
                  duration: 245,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "WAV",
                  fileSize: 41234567,
                  enrichmentStatus: "pending",
                  sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
                },
              },
              {
                id: "track-cd2",
                name: "02 - track.wav",
                type: "audio",
                path: `${SOURCE_ROOT}/CD Rips/Disc1/02 - track.wav`,
                parentId: "folder-disc1",
                metadata: {
                  title: "Track 02",
                  artist: "Unknown Artist",
                  album: "Disc1",
                  year: 0,
                  genre: "Unknown",
                  duration: 198,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "WAV",
                  fileSize: 33456789,
                  enrichmentStatus: "pending",
                  sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
                },
              },
            ],
          },
        ],
      },
      // Messy: Downloads with date subfolder
      {
        id: "folder-downloads",
        name: "Downloads",
        type: "folder",
        path: `${SOURCE_ROOT}/Downloads`,
        parentId: "root",
        children: [
          {
            id: "folder-2020-03",
            name: "2020-03",
            type: "folder",
            path: `${SOURCE_ROOT}/Downloads/2020-03`,
            parentId: "folder-downloads",
            children: [
              {
                id: "track-dl1",
                name: "random_song.mp3",
                type: "audio",
                path: `${SOURCE_ROOT}/Downloads/2020-03/random_song.mp3`,
                parentId: "folder-2020-03",
                metadata: {
                  title: "Random Song",
                  artist: "Various Artists",
                  album: "Unknown",
                  year: 2020,
                  genre: "Pop",
                  duration: 223,
                  bitrate: 256,
                  sampleRate: 44100,
                  format: "MP3",
                  fileSize: 7123456,
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: false, spotify: true, genius: false },
                },
              },
            ],
          },
        ],
      },
      // The Beatles – partly organized, with messy duplicate folder
      {
        id: "artist-1",
        name: "The Beatles",
        type: "folder",
        path: `${SOURCE_ROOT}/The Beatles`,
        parentId: "root",
        children: [
          {
            id: "album-1",
            name: "Abbey Road",
            type: "folder",
            path: `${SOURCE_ROOT}/The Beatles/Abbey Road`,
            parentId: "artist-1",
            children: [
              {
                id: "track-1",
                name: "Come Together.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/The Beatles/Abbey Road/Come Together.flac`,
                parentId: "album-1",
                metadata: {
                  title: "Come Together",
                  artist: "The Beatles",
                  album: "Abbey Road",
                  year: 1969,
                  genre: "Rock",
                  duration: 259,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 45678912,
                  albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
                  lyrics: `Here come old flat top\nHe come grooving up slowly\nHe got joo joo eyeball\nHe one holy roller\nHe got hair down to his knee\nGot to be a joker, he just do what he please\n\nHe wear no shoeshine\nHe got toe-jam football\nHe got monkey finger\nHe shoot Coca-Cola\nHe say, "I know you, you know me"\nOne thing I can tell you is you got to be free\n\nCome together, right now\nOver me`,
                  fingerprint: "AQADtNIyRZIkSZEUJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-2",
                name: "Something.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/The Beatles/Abbey Road/Something.flac`,
                parentId: "album-1",
                metadata: {
                  title: "Something",
                  artist: "The Beatles",
                  album: "Abbey Road",
                  year: 1969,
                  genre: "Rock",
                  duration: 182,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 32156789,
                  albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
                  fingerprint: "AQADtNIyRZIkTZEkJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: false },
                },
              },
              {
                id: "track-3",
                name: "Here Comes The Sun.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/The Beatles/Abbey Road/Here Comes The Sun.flac`,
                parentId: "album-1",
                metadata: {
                  title: "Here Comes The Sun",
                  artist: "The Beatles",
                  album: "Abbey Road",
                  year: 1969,
                  genre: "Rock",
                  duration: 185,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 32678912,
                  albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
                  lyrics: `Here comes the sun, doo-doo-doo-doo\nHere comes the sun\nAnd I say, "It's all right"\n\nLittle darling, it's been a long cold lonely winter\nLittle darling, it feels like years since it's been here\n\nHere comes the sun\nHere comes the sun\nAnd I say, "It's all right"`,
                  fingerprint: "AQADtNIyRZIkSZEUSXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
            ],
          },
          {
            id: "album-2",
            name: "Let It Be",
            type: "folder",
            path: `${SOURCE_ROOT}/The Beatles/Let It Be`,
            parentId: "artist-1",
            children: [
              {
                id: "track-4",
                name: "Let It Be.mp3",
                type: "audio",
                path: `${SOURCE_ROOT}/The Beatles/Let It Be/Let It Be.mp3`,
                parentId: "album-2",
                metadata: {
                  title: "Let It Be",
                  artist: "The Beatles",
                  album: "Let It Be",
                  year: 1970,
                  genre: "Rock",
                  duration: 243,
                  bitrate: 320,
                  sampleRate: 44100,
                  format: "MP3",
                  fileSize: 9756123,
                  albumArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
                  enrichmentStatus: "processing",
                  sources: { musicbrainz: true, lastfm: true, spotify: false, genius: false },
                },
              },
            ],
          },
          // Messy: duplicate-style folder with one stray
          {
            id: "album-1-dup",
            name: "Abbey Road (1)",
            type: "folder",
            path: `${SOURCE_ROOT}/The Beatles/Abbey Road (1)`,
            parentId: "artist-1",
            children: [
              {
                id: "track-3-dup",
                name: "Here Comes The Sun.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/The Beatles/Abbey Road (1)/Here Comes The Sun.flac`,
                parentId: "album-1-dup",
                metadata: {
                  title: "Here Comes The Sun",
                  artist: "The Beatles",
                  album: "Abbey Road",
                  year: 1969,
                  genre: "Rock",
                  duration: 185,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 32678912,
                  albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
            ],
          },
        ],
      },
      // Pink Floyd – album folder + loose file at artist level
      {
        id: "artist-2",
        name: "Pink Floyd",
        type: "folder",
        path: `${SOURCE_ROOT}/Pink Floyd`,
        parentId: "root",
        children: [
          {
            id: "track-5-loose",
            name: "time_backup.flac",
            type: "audio",
            path: `${SOURCE_ROOT}/Pink Floyd/time_backup.flac`,
            parentId: "artist-2",
            metadata: {
              title: "Time",
              artist: "Pink Floyd",
              album: "The Dark Side of the Moon",
              year: 1973,
              genre: "Progressive Rock",
              duration: 413,
              bitrate: 1411,
              sampleRate: 44100,
              format: "FLAC",
              fileSize: 72891234,
              albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
              fingerprint: "BQBDtNIyRZIkSZEkJXmO44iS5DiO",
              enrichmentStatus: "complete",
              sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
            },
          },
          {
            id: "album-3",
            name: "The Dark Side of the Moon",
            type: "folder",
            path: `${SOURCE_ROOT}/Pink Floyd/The Dark Side of the Moon`,
            parentId: "artist-2",
            children: [
              {
                id: "track-5",
                name: "Time.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Pink Floyd/The Dark Side of the Moon/Time.flac`,
                parentId: "album-3",
                metadata: {
                  title: "Time",
                  artist: "Pink Floyd",
                  album: "The Dark Side of the Moon",
                  year: 1973,
                  genre: "Progressive Rock",
                  duration: 413,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 72891234,
                  albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
                  lyrics: `Ticking away the moments that make up a dull day\nFritter and waste the hours in an offhand way\nKicking around on a piece of ground in your hometown\nWaiting for someone or something to show you the way\n\nTired of lying in the sunshine, staying home to watch the rain\nYou are young and life is long, and there is time to kill today\nAnd then one day you find ten years have got behind you\nNo one told you when to run, you missed the starting gun`,
                  fingerprint: "BQBDtNIyRZIkSZEkJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-6",
                name: "Money.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Pink Floyd/The Dark Side of the Moon/Money.flac`,
                parentId: "album-3",
                metadata: {
                  title: "Money",
                  artist: "Pink Floyd",
                  album: "The Dark Side of the Moon",
                  year: 1973,
                  genre: "Progressive Rock",
                  duration: 382,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 67456789,
                  albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
                  fingerprint: "BQBDtNIyRZIkSZEkJXnO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: false },
                },
              },
              {
                id: "track-7",
                name: "Us and Them.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Pink Floyd/The Dark Side of the Moon/Us and Them.flac`,
                parentId: "album-3",
                metadata: {
                  title: "Us and Them",
                  artist: "Pink Floyd",
                  album: "The Dark Side of the Moon",
                  year: 1973,
                  genre: "Progressive Rock",
                  duration: 469,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 82789456,
                  albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
                  enrichmentStatus: "pending",
                  sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
                },
              },
            ],
          },
        ],
      },
      {
        id: "artist-3",
        name: "Daft Punk",
        type: "folder",
        path: `${SOURCE_ROOT}/Daft Punk`,
        parentId: "root",
        children: [
          {
            id: "album-4",
            name: "Random Access Memories",
            type: "folder",
            path: `${SOURCE_ROOT}/Daft Punk/Random Access Memories`,
            parentId: "artist-3",
            children: [
              {
                id: "track-8",
                name: "Get Lucky.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Daft Punk/Random Access Memories/Get Lucky.flac`,
                parentId: "album-4",
                metadata: {
                  title: "Get Lucky",
                  artist: "Daft Punk ft. Pharrell Williams",
                  album: "Random Access Memories",
                  year: 2013,
                  genre: "Electronic",
                  duration: 369,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 65123456,
                  albumArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
                  lyrics: `Like the legend of the phoenix\nAll ends with beginnings\nWhat keeps the planet spinning\nThe force from the beginning\n\nWe've come too far to give up who we are\nSo let's raise the bar and our cups to the stars\n\nShe's up all night 'til the sun\nI'm up all night to get some\nShe's up all night for good fun\nI'm up all night to get lucky`,
                  fingerprint: "CQCDtNIyRZIkSZEkJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-9",
                name: "Instant Crush.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Daft Punk/Random Access Memories/Instant Crush.flac`,
                parentId: "album-4",
                metadata: {
                  title: "Instant Crush",
                  artist: "Daft Punk ft. Julian Casablancas",
                  album: "Random Access Memories",
                  year: 2013,
                  genre: "Electronic",
                  duration: 337,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 59456789,
                  albumArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
                  enrichmentStatus: "failed",
                  sources: { musicbrainz: true, lastfm: false, spotify: false, genius: false },
                },
              },
            ],
          },
        ],
      },
      {
        id: "artist-4",
        name: "Radiohead",
        type: "folder",
        path: `${SOURCE_ROOT}/Radiohead`,
        parentId: "root",
        children: [
          {
            id: "album-5",
            name: "OK Computer",
            type: "folder",
            path: `${SOURCE_ROOT}/Radiohead/OK Computer`,
            parentId: "artist-4",
            children: [
              {
                id: "track-10",
                name: "Paranoid Android.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Radiohead/OK Computer/Paranoid Android.flac`,
                parentId: "album-5",
                metadata: {
                  title: "Paranoid Android",
                  artist: "Radiohead",
                  album: "OK Computer",
                  year: 1997,
                  genre: "Alternative Rock",
                  duration: 386,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 68123456,
                  albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-11",
                name: "Karma Police.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Radiohead/OK Computer/Karma Police.flac`,
                parentId: "album-5",
                metadata: {
                  title: "Karma Police",
                  artist: "Radiohead",
                  album: "OK Computer",
                  year: 1997,
                  genre: "Alternative Rock",
                  duration: 264,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 46567890,
                  albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
                  lyrics: `Karma police, arrest this man\nHe talks in maths, he buzzes like a fridge\nHe's like a detuned radio\n\nKarma police, arrest this girl\nHer Hitler hairdo is making me feel ill\nAnd we have crashed her party\n\nThis is what you get\nThis is what you get\nThis is what you get\nWhen you mess with us`,
                  fingerprint: "DQDDtNIyRZIkSZEkJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
            ],
          },
        ],
      },
      // Messy: inconsistent naming
      {
        id: "artist-1-alt",
        name: "the beatles",
        type: "folder",
        path: `${SOURCE_ROOT}/the beatles`,
        parentId: "root",
        children: [
          {
            id: "album-2-alt",
            name: "let it be",
            type: "folder",
            path: `${SOURCE_ROOT}/the beatles/let it be`,
            parentId: "artist-1-alt",
            children: [
              {
                id: "track-4-alt",
                name: "get back.mp3",
                type: "audio",
                path: `${SOURCE_ROOT}/the beatles/let it be/get back.mp3`,
                parentId: "album-2-alt",
                metadata: {
                  title: "Get Back",
                  artist: "The Beatles",
                  album: "Let It Be",
                  year: 1970,
                  genre: "Rock",
                  duration: 191,
                  bitrate: 320,
                  sampleRate: 44100,
                  format: "MP3",
                  fileSize: 7654321,
                  albumArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: false },
                },
              },
            ],
          },
        ],
      },
      // New artists: Fleetwood Mac, Nirvana, David Bowie
      {
        id: "artist-5",
        name: "Fleetwood Mac",
        type: "folder",
        path: `${SOURCE_ROOT}/Fleetwood Mac`,
        parentId: "root",
        children: [
          {
            id: "album-6",
            name: "Rumours",
            type: "folder",
            path: `${SOURCE_ROOT}/Fleetwood Mac/Rumours`,
            parentId: "artist-5",
            children: [
              {
                id: "track-fm1",
                name: "Go Your Own Way.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Fleetwood Mac/Rumours/Go Your Own Way.flac`,
                parentId: "album-6",
                metadata: {
                  title: "Go Your Own Way",
                  artist: "Fleetwood Mac",
                  album: "Rumours",
                  year: 1977,
                  genre: "Rock",
                  duration: 214,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 37891234,
                  albumArt: "https://images.unsplash.com/photo-1484755560615-a4c64e778a6c?w=400&h=400&fit=crop",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-fm2",
                name: "Dreams.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Fleetwood Mac/Rumours/Dreams.flac`,
                parentId: "album-6",
                metadata: {
                  title: "Dreams",
                  artist: "Fleetwood Mac",
                  album: "Rumours",
                  year: 1977,
                  genre: "Rock",
                  duration: 250,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 44123456,
                  albumArt: "https://images.unsplash.com/photo-1484755560615-a4c64e778a6c?w=400&h=400&fit=crop",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
            ],
          },
        ],
      },
      {
        id: "artist-6",
        name: "Nirvana",
        type: "folder",
        path: `${SOURCE_ROOT}/Nirvana`,
        parentId: "root",
        children: [
          {
            id: "album-7",
            name: "Nevermind",
            type: "folder",
            path: `${SOURCE_ROOT}/Nirvana/Nevermind`,
            parentId: "artist-6",
            children: [
              {
                id: "track-nv1",
                name: "Smells Like Teen Spirit.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Nirvana/Nevermind/Smells Like Teen Spirit.flac`,
                parentId: "album-7",
                metadata: {
                  title: "Smells Like Teen Spirit",
                  artist: "Nirvana",
                  album: "Nevermind",
                  year: 1991,
                  genre: "Grunge",
                  duration: 301,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 53123456,
                  albumArt: "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-nv2",
                name: "Come As You Are.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Nirvana/Nevermind/Come As You Are.flac`,
                parentId: "album-7",
                metadata: {
                  title: "Come As You Are",
                  artist: "Nirvana",
                  album: "Nevermind",
                  year: 1991,
                  genre: "Grunge",
                  duration: 219,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 38678901,
                  albumArt: "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: false },
                },
              },
            ],
          },
        ],
      },
      {
        id: "artist-7",
        name: "David Bowie",
        type: "folder",
        path: `${SOURCE_ROOT}/David Bowie`,
        parentId: "root",
        children: [
          {
            id: "album-8",
            name: "The Rise and Fall of Ziggy Stardust",
            type: "folder",
            path: `${SOURCE_ROOT}/David Bowie/The Rise and Fall of Ziggy Stardust`,
            parentId: "artist-7",
            children: [
              {
                id: "track-db1",
                name: "Starman.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/David Bowie/The Rise and Fall of Ziggy Stardust/Starman.flac`,
                parentId: "album-8",
                metadata: {
                  title: "Starman",
                  artist: "David Bowie",
                  album: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
                  year: 1972,
                  genre: "Rock",
                  duration: 256,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 45123456,
                  albumArt: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-db2",
                name: "Suffragette City.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/David Bowie/The Rise and Fall of Ziggy Stardust/Suffragette City.flac`,
                parentId: "album-8",
                metadata: {
                  title: "Suffragette City",
                  artist: "David Bowie",
                  album: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
                  year: 1972,
                  genre: "Rock",
                  duration: 201,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 35456789,
                  albumArt: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop",
                  enrichmentStatus: "processing",
                  sources: { musicbrainz: true, lastfm: true, spotify: false, genius: false },
                },
              },
            ],
          },
        ],
      },
      {
        id: "unsorted",
        name: "Unsorted",
        type: "folder",
        path: `${SOURCE_ROOT}/Unsorted`,
        parentId: "root",
        children: [
          {
            id: "track-12",
            name: "unknown_track_001.mp3",
            type: "audio",
            path: `${SOURCE_ROOT}/Unsorted/unknown_track_001.mp3`,
            parentId: "unsorted",
            metadata: {
              title: "Unknown Track",
              artist: "Unknown Artist",
              album: "Unknown Album",
              year: 0,
              genre: "Unknown",
              duration: 234,
              bitrate: 192,
              sampleRate: 44100,
              format: "MP3",
              fileSize: 5623456,
              enrichmentStatus: "pending",
              sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
            },
          },
          {
            id: "track-13",
            name: "mystery_song.wav",
            type: "audio",
            path: `${SOURCE_ROOT}/Unsorted/mystery_song.wav`,
            parentId: "unsorted",
            metadata: {
              title: "Mystery Song",
              artist: "Unknown",
              album: "Unknown",
              year: 0,
              genre: "Unknown",
              duration: 198,
              bitrate: 1411,
              sampleRate: 44100,
              format: "WAV",
              fileSize: 34891234,
              enrichmentStatus: "processing",
              sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
            },
          },
        ],
      },
    ],
  },
]

export const mockImportJob: ImportJob = {
  id: "job-1",
  sourcePath: "/Volumes/music",
  destinationPath: "/Music Library",
  status: "running",
  startedAt: new Date(Date.now() - 1000 * 60 * 45), // 45 mins ago
  tracksDiscovered: 847,
  tracksProcessed: 623,
  tracksCopied: 589,
  tracksReview: 18,
  tracksFailed: 16,
}

export const mockTracksForReview: TrackImport[] = [
  {
    id: "review-1",
    originalPath: "/Volumes/External/Music Import/Unknown/track01.mp3",
    status: "review",
    metadata: {
      title: "Track 01",
      artist: "Unknown Artist",
      album: "Unknown Album",
      year: 0,
      genre: "Unknown",
      duration: 234,
      bitrate: 320,
      sampleRate: 44100,
      format: "MP3",
      fileSize: 9345678,
      enrichmentStatus: "complete",
      sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
    },
    suggestedMetadata: {
      title: "Bohemian Rhapsody",
      artist: "Queen",
      album: "A Night at the Opera",
      year: 1975,
      genre: "Rock",
      albumArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    },
    issues: ["Low confidence match (67%)", "Multiple potential matches found"],
    fingerprint: "AQADtNIyRZIkSZEkJXmO44iS5DiO",
  },
  {
    id: "review-2",
    originalPath: "/Volumes/External/Music Import/Downloads/song.flac",
    status: "review",
    metadata: {
      title: "song",
      artist: "Unknown",
      album: "Unknown",
      year: 0,
      genre: "Unknown",
      duration: 312,
      bitrate: 1411,
      sampleRate: 44100,
      format: "FLAC",
      fileSize: 55123456,
      enrichmentStatus: "complete",
      sources: { musicbrainz: true, lastfm: false, spotify: false, genius: false },
    },
    suggestedMetadata: {
      title: "Stairway to Heaven",
      artist: "Led Zeppelin",
      album: "Led Zeppelin IV",
      year: 1971,
      genre: "Rock",
      albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    },
    issues: ["Metadata mismatch with filename"],
    fingerprint: "BQBDtNIyRZIkSZEkJXmO44iS5DiO",
  },
  {
    id: "review-3",
    originalPath: "/Volumes/External/Music Import/CDs/Disc1/03.wav",
    status: "review",
    metadata: {
      title: "03",
      artist: "Unknown",
      album: "Disc1",
      year: 0,
      genre: "Unknown",
      duration: 267,
      bitrate: 1411,
      sampleRate: 44100,
      format: "WAV",
      fileSize: 47123456,
      enrichmentStatus: "complete",
      sources: { musicbrainz: true, lastfm: true, spotify: false, genius: false },
    },
    suggestedMetadata: {
      title: "Hotel California",
      artist: "Eagles",
      album: "Hotel California",
      year: 1977,
      genre: "Rock",
      albumArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
    },
    issues: ["No embedded metadata", "Confidence: 89%"],
    fingerprint: "CQCDtNIyRZIkSZEkJXmO44iS5DiO",
  },
  {
    id: "review-4",
    originalPath: "/Volumes/External/Music Import/Rips/album/track_04.flac",
    status: "review",
    metadata: {
      title: "Track 4",
      artist: "Various Artists",
      album: "Compilation",
      year: 2020,
      genre: "Pop",
      duration: 198,
      bitrate: 1411,
      sampleRate: 44100,
      format: "FLAC",
      fileSize: 35000000,
      enrichmentStatus: "complete",
      sources: { musicbrainz: false, lastfm: false, spotify: true, genius: false },
    },
    suggestedMetadata: {
      title: "Billie Jean",
      artist: "Michael Jackson",
      album: "Thriller",
      year: 1982,
      genre: "Pop",
      albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
    },
    issues: ["Existing metadata conflicts with fingerprint match"],
    fingerprint: "DQDDtNIyRZIkSZEkJXmO44iS5DiO",
  },
  {
    id: "review-5",
    originalPath: "/Volumes/External/Music Import/New/untitled.mp3",
    status: "review",
    metadata: {
      title: "Untitled",
      artist: "",
      album: "",
      year: 0,
      genre: "Unknown",
      duration: 245,
      bitrate: 256,
      sampleRate: 44100,
      format: "MP3",
      fileSize: 7800000,
      enrichmentStatus: "failed",
      sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
    },
    issues: ["No fingerprint match found", "Manual entry required"],
    fingerprint: undefined,
  },
  {
    id: "review-6",
    originalPath: "/Volumes/External/Music Import/Archive/old_recording.wav",
    status: "review",
    metadata: {
      title: "Old Recording",
      artist: "Home Recording",
      album: "Personal",
      year: 1995,
      genre: "Unknown",
      duration: 356,
      bitrate: 1411,
      sampleRate: 44100,
      format: "WAV",
      fileSize: 62000000,
      enrichmentStatus: "complete",
      sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
    },
    suggestedMetadata: {
      title: "Wish You Were Here",
      artist: "Pink Floyd",
      album: "Wish You Were Here",
      year: 1975,
      genre: "Progressive Rock",
      albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    },
    issues: ["Low audio quality detected", "Possible live recording"],
    fingerprint: "EQEDtNIyRZIkSZEkJXmO44iS5DiO",
  },
]

export const mockRecentActivity = [
  { id: "act-1", type: "discovered" as const, track: "Come Together.flac", artist: "The Beatles", time: "2 min ago" },
  { id: "act-2", type: "copied" as const, track: "Something.flac", artist: "The Beatles", time: "3 min ago" },
  { id: "act-3", type: "enriched" as const, track: "Dreams.flac", artist: "Fleetwood Mac", time: "4 min ago" },
  { id: "act-4", type: "review" as const, track: "unknown_track.mp3", artist: "Unknown", time: "6 min ago" },
  { id: "act-5", type: "copied" as const, track: "Time.flac", artist: "Pink Floyd", time: "8 min ago" },
  { id: "act-6", type: "failed" as const, track: "corrupted_file.mp3", artist: "Unknown", time: "10 min ago" },
  { id: "act-7", type: "discovered" as const, track: "Smells Like Teen Spirit.flac", artist: "Nirvana", time: "12 min ago" },
  { id: "act-8", type: "enriched" as const, track: "Get Lucky.flac", artist: "Daft Punk", time: "15 min ago" },
]

// Artists in library
export const mockArtists: Artist[] = [
  {
    id: "artist-beatles",
    name: "The Beatles",
    image: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
    genres: ["Rock", "Pop"],
    albumsInLibrary: 3,
    totalAlbums: 13,
    tracksInLibrary: 6,
    totalTracks: 213,
  },
  {
    id: "artist-pinkfloyd",
    name: "Pink Floyd",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    genres: ["Progressive Rock", "Psychedelic Rock"],
    albumsInLibrary: 1,
    totalAlbums: 15,
    tracksInLibrary: 4,
    totalTracks: 165,
  },
  {
    id: "artist-daftpunk",
    name: "Daft Punk",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
    genres: ["Electronic", "House"],
    albumsInLibrary: 1,
    totalAlbums: 4,
    tracksInLibrary: 2,
    totalTracks: 52,
  },
  {
    id: "artist-radiohead",
    name: "Radiohead",
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
    genres: ["Alternative Rock", "Art Rock"],
    albumsInLibrary: 1,
    totalAlbums: 9,
    tracksInLibrary: 2,
    totalTracks: 101,
  },
  {
    id: "artist-fleetwoodmac",
    name: "Fleetwood Mac",
    image: "https://images.unsplash.com/photo-1484755560615-a4c64e778a6c?w=400&h=400&fit=crop",
    genres: ["Rock", "Soft Rock"],
    albumsInLibrary: 1,
    totalAlbums: 18,
    tracksInLibrary: 2,
    totalTracks: 142,
  },
  {
    id: "artist-nirvana",
    name: "Nirvana",
    image: "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop",
    genres: ["Grunge", "Alternative Rock"],
    albumsInLibrary: 1,
    totalAlbums: 3,
    tracksInLibrary: 2,
    totalTracks: 49,
  },
  {
    id: "artist-davidbowie",
    name: "David Bowie",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop",
    genres: ["Rock", "Art Rock", "Glam Rock"],
    albumsInLibrary: 1,
    totalAlbums: 26,
    tracksInLibrary: 2,
    totalTracks: 287,
  },
]

// Full discography for The Beatles
export const mockBeatlesDiscography: DiscographyAlbum[] = [
  {
    id: "disc-abbey",
    name: "Abbey Road",
    year: 1969,
    albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
    type: "album",
    inLibrary: true,
    tracksOwned: 3,
    totalTracks: 17,
    tracks: [
      { id: "t1", name: "Come Together", trackNumber: 1, duration: 259, inLibrary: true, downloadStatus: "downloaded" },
      { id: "t2", name: "Something", trackNumber: 2, duration: 182, inLibrary: true, downloadStatus: "downloaded" },
      { id: "t3", name: "Maxwell's Silver Hammer", trackNumber: 3, duration: 207, inLibrary: false, downloadStatus: "available" },
      { id: "t4", name: "Oh! Darling", trackNumber: 4, duration: 206, inLibrary: false, downloadStatus: "available" },
      { id: "t5", name: "Octopus's Garden", trackNumber: 5, duration: 171, inLibrary: false, downloadStatus: "available" },
      { id: "t6", name: "I Want You (She's So Heavy)", trackNumber: 6, duration: 467, inLibrary: false, downloadStatus: "available" },
      { id: "t7", name: "Here Comes The Sun", trackNumber: 7, duration: 185, inLibrary: true, downloadStatus: "downloaded" },
      { id: "t8", name: "Because", trackNumber: 8, duration: 165, inLibrary: false, downloadStatus: "available" },
      { id: "t9", name: "You Never Give Me Your Money", trackNumber: 9, duration: 242, inLibrary: false, downloadStatus: "available" },
      { id: "t10", name: "Sun King", trackNumber: 10, duration: 146, inLibrary: false, downloadStatus: "available" },
      { id: "t11", name: "Mean Mr. Mustard", trackNumber: 11, duration: 66, inLibrary: false, downloadStatus: "available" },
      { id: "t12", name: "Polythene Pam", trackNumber: 12, duration: 72, inLibrary: false, downloadStatus: "available" },
      { id: "t13", name: "She Came In Through the Bathroom Window", trackNumber: 13, duration: 118, inLibrary: false, downloadStatus: "available" },
      { id: "t14", name: "Golden Slumbers", trackNumber: 14, duration: 91, inLibrary: false, downloadStatus: "available" },
      { id: "t15", name: "Carry That Weight", trackNumber: 15, duration: 97, inLibrary: false, downloadStatus: "available" },
      { id: "t16", name: "The End", trackNumber: 16, duration: 140, inLibrary: false, downloadStatus: "available" },
      { id: "t17", name: "Her Majesty", trackNumber: 17, duration: 23, inLibrary: false, downloadStatus: "available" },
    ],
  },
  {
    id: "disc-letitbe",
    name: "Let It Be",
    year: 1970,
    albumArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    type: "album",
    inLibrary: true,
    tracksOwned: 1,
    totalTracks: 12,
    tracks: [
      { id: "t18", name: "Two of Us", trackNumber: 1, duration: 214, inLibrary: false, downloadStatus: "available" },
      { id: "t19", name: "Dig a Pony", trackNumber: 2, duration: 235, inLibrary: false, downloadStatus: "available" },
      { id: "t20", name: "Across the Universe", trackNumber: 3, duration: 228, inLibrary: false, downloadStatus: "available" },
      { id: "t21", name: "I Me Mine", trackNumber: 4, duration: 136, inLibrary: false, downloadStatus: "available" },
      { id: "t22", name: "Dig It", trackNumber: 5, duration: 51, inLibrary: false, downloadStatus: "available" },
      { id: "t23", name: "Let It Be", trackNumber: 6, duration: 243, inLibrary: true, downloadStatus: "downloaded" },
      { id: "t24", name: "Maggie Mae", trackNumber: 7, duration: 40, inLibrary: false, downloadStatus: "available" },
      { id: "t25", name: "I've Got a Feeling", trackNumber: 8, duration: 217, inLibrary: false, downloadStatus: "available" },
      { id: "t26", name: "One After 909", trackNumber: 9, duration: 170, inLibrary: false, downloadStatus: "available" },
      { id: "t27", name: "The Long and Winding Road", trackNumber: 10, duration: 222, inLibrary: false, downloadStatus: "available" },
      { id: "t28", name: "For You Blue", trackNumber: 11, duration: 152, inLibrary: false, downloadStatus: "available" },
      { id: "t29", name: "Get Back", trackNumber: 12, duration: 191, inLibrary: false, downloadStatus: "available" },
    ],
  },
  {
    id: "disc-whitea",
    name: "The Beatles (White Album)",
    year: 1968,
    albumArt: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop",
    type: "album",
    inLibrary: false,
    tracksOwned: 0,
    totalTracks: 30,
    tracks: [
      { id: "t30", name: "Back in the U.S.S.R.", trackNumber: 1, duration: 163, inLibrary: false, downloadStatus: "available" },
      { id: "t31", name: "Dear Prudence", trackNumber: 2, duration: 236, inLibrary: false, downloadStatus: "available" },
      { id: "t32", name: "Glass Onion", trackNumber: 3, duration: 132, inLibrary: false, downloadStatus: "available" },
      { id: "t33", name: "Ob-La-Di, Ob-La-Da", trackNumber: 4, duration: 189, inLibrary: false, downloadStatus: "available" },
      { id: "t34", name: "Wild Honey Pie", trackNumber: 5, duration: 54, inLibrary: false, downloadStatus: "available" },
      { id: "t35", name: "The Continuing Story of Bungalow Bill", trackNumber: 6, duration: 191, inLibrary: false, downloadStatus: "available" },
      { id: "t36", name: "While My Guitar Gently Weeps", trackNumber: 7, duration: 284, inLibrary: false, downloadStatus: "available" },
      { id: "t37", name: "Happiness Is a Warm Gun", trackNumber: 8, duration: 163, inLibrary: false, downloadStatus: "available" },
      { id: "t38", name: "Martha My Dear", trackNumber: 9, duration: 148, inLibrary: false, downloadStatus: "available" },
      { id: "t39", name: "Blackbird", trackNumber: 10, duration: 138, inLibrary: false, downloadStatus: "available" },
    ],
  },
  {
    id: "disc-sgtpepper",
    name: "Sgt. Pepper's Lonely Hearts Club Band",
    year: 1967,
    albumArt: "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop",
    type: "album",
    inLibrary: false,
    tracksOwned: 0,
    totalTracks: 13,
    tracks: [
      { id: "t40", name: "Sgt. Pepper's Lonely Hearts Club Band", trackNumber: 1, duration: 122, inLibrary: false, downloadStatus: "available" },
      { id: "t41", name: "With a Little Help from My Friends", trackNumber: 2, duration: 164, inLibrary: false, downloadStatus: "available" },
      { id: "t42", name: "Lucy in the Sky with Diamonds", trackNumber: 3, duration: 207, inLibrary: false, downloadStatus: "available" },
      { id: "t43", name: "Getting Better", trackNumber: 4, duration: 167, inLibrary: false, downloadStatus: "available" },
      { id: "t44", name: "Fixing a Hole", trackNumber: 5, duration: 156, inLibrary: false, downloadStatus: "available" },
      { id: "t45", name: "She's Leaving Home", trackNumber: 6, duration: 215, inLibrary: false, downloadStatus: "available" },
      { id: "t46", name: "Being for the Benefit of Mr. Kite!", trackNumber: 7, duration: 157, inLibrary: false, downloadStatus: "available" },
      { id: "t47", name: "Within You Without You", trackNumber: 8, duration: 305, inLibrary: false, downloadStatus: "available" },
      { id: "t48", name: "When I'm Sixty-Four", trackNumber: 9, duration: 157, inLibrary: false, downloadStatus: "available" },
      { id: "t49", name: "Lovely Rita", trackNumber: 10, duration: 162, inLibrary: false, downloadStatus: "available" },
      { id: "t50", name: "Good Morning Good Morning", trackNumber: 11, duration: 161, inLibrary: false, downloadStatus: "available" },
      { id: "t51", name: "Sgt. Pepper's Lonely Hearts Club Band (Reprise)", trackNumber: 12, duration: 79, inLibrary: false, downloadStatus: "available" },
      { id: "t52", name: "A Day in the Life", trackNumber: 13, duration: 337, inLibrary: false, downloadStatus: "available" },
    ],
  },
  {
    id: "disc-revolver",
    name: "Revolver",
    year: 1966,
    albumArt: "https://images.unsplash.com/photo-1484755560615-a4c64e778a6c?w=400&h=400&fit=crop",
    type: "album",
    inLibrary: false,
    tracksOwned: 0,
    totalTracks: 14,
    tracks: [
      { id: "t53", name: "Taxman", trackNumber: 1, duration: 159, inLibrary: false, downloadStatus: "available" },
      { id: "t54", name: "Eleanor Rigby", trackNumber: 2, duration: 126, inLibrary: false, downloadStatus: "available" },
      { id: "t55", name: "I'm Only Sleeping", trackNumber: 3, duration: 181, inLibrary: false, downloadStatus: "available" },
      { id: "t56", name: "Love You To", trackNumber: 4, duration: 180, inLibrary: false, downloadStatus: "available" },
      { id: "t57", name: "Here, There and Everywhere", trackNumber: 5, duration: 145, inLibrary: false, downloadStatus: "available" },
      { id: "t58", name: "Yellow Submarine", trackNumber: 6, duration: 159, inLibrary: false, downloadStatus: "available" },
    ],
  },
]

// Spotify playlists and tracks
export const mockSpotifyPlaylists: SpotifyPlaylist[] = [
  {
    id: "sp-liked",
    name: "Liked Songs",
    description: "Your saved tracks",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    trackCount: 847,
    owner: "You",
    syncStatus: "partial",
    tracksMatched: 234,
    lastSynced: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
  {
    id: "sp-discover",
    name: "Discover Weekly",
    description: "Your weekly mixtape of fresh music",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
    trackCount: 30,
    owner: "Spotify",
    syncStatus: "not_synced",
    tracksMatched: 0,
  },
  {
    id: "sp-rock",
    name: "Classic Rock Hits",
    description: "The best of classic rock",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    trackCount: 156,
    owner: "You",
    syncStatus: "synced",
    tracksMatched: 142,
    lastSynced: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: "sp-chill",
    name: "Chill Vibes",
    description: "Relaxing tunes for any mood",
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
    trackCount: 89,
    owner: "You",
    syncStatus: "syncing",
    tracksMatched: 45,
  },
  {
    id: "sp-workout",
    name: "Workout Mix",
    description: "High energy tracks",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop",
    trackCount: 67,
    owner: "You",
    syncStatus: "not_synced",
    tracksMatched: 0,
  },
]

export const mockSpotifyLikedSongs: SpotifyTrack[] = [
  { id: "spt-1", name: "Come Together", artist: "The Beatles", album: "Abbey Road", albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop", duration: 259, inLibrary: true, matchConfidence: 100 },
  { id: "spt-2", name: "Bohemian Rhapsody", artist: "Queen", album: "A Night at the Opera", albumArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop", duration: 354, inLibrary: false, matchConfidence: undefined },
  { id: "spt-3", name: "Time", artist: "Pink Floyd", album: "The Dark Side of the Moon", albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop", duration: 413, inLibrary: true, matchConfidence: 100 },
  { id: "spt-4", name: "Stairway to Heaven", artist: "Led Zeppelin", album: "Led Zeppelin IV", albumArt: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop", duration: 482, inLibrary: false, matchConfidence: undefined },
  { id: "spt-5", name: "Get Lucky", artist: "Daft Punk", album: "Random Access Memories", albumArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop", duration: 369, inLibrary: true, matchConfidence: 100 },
  { id: "spt-6", name: "Hotel California", artist: "Eagles", album: "Hotel California", albumArt: "https://images.unsplash.com/photo-1484755560615-a4c64e778a6c?w=400&h=400&fit=crop", duration: 391, inLibrary: false, matchConfidence: undefined },
  { id: "spt-7", name: "Karma Police", artist: "Radiohead", album: "OK Computer", albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop", duration: 264, inLibrary: true, matchConfidence: 100 },
  { id: "spt-8", name: "Wish You Were Here", artist: "Pink Floyd", album: "Wish You Were Here", albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop", duration: 307, inLibrary: false, matchConfidence: undefined },
  { id: "spt-9", name: "Paranoid Android", artist: "Radiohead", album: "OK Computer", albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop", duration: 386, inLibrary: true, matchConfidence: 100 },
  { id: "spt-10", name: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", albumArt: "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop", duration: 301, inLibrary: false, matchConfidence: undefined },
  { id: "spt-11", name: "Money", artist: "Pink Floyd", album: "The Dark Side of the Moon", albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop", duration: 382, inLibrary: true, matchConfidence: 100 },
  { id: "spt-12", name: "Sweet Child O' Mine", artist: "Guns N' Roses", album: "Appetite for Destruction", albumArt: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop", duration: 356, inLibrary: false, matchConfidence: undefined },
  { id: "spt-13", name: "Dreams", artist: "Fleetwood Mac", album: "Rumours", albumArt: "https://images.unsplash.com/photo-1484755560615-a4c64e778a6c?w=400&h=400&fit=crop", duration: 250, inLibrary: true, matchConfidence: 100 },
  { id: "spt-14", name: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", albumArt: "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop", duration: 301, inLibrary: true, matchConfidence: 100 },
  { id: "spt-15", name: "Starman", artist: "David Bowie", album: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", albumArt: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop", duration: 256, inLibrary: true, matchConfidence: 100 },
]

export function findFileById(files: FileItem[], id: string): FileItem | null {
  for (const file of files) {
    if (file.id === id) return file
    if (file.children) {
      const found = findFileById(file.children, id)
      if (found) return found
    }
  }
  return null
}

export function getPathToFile(files: FileItem[], targetId: string): FileItem[] {
  const path: FileItem[] = []
  
  function search(items: FileItem[], target: string): boolean {
    for (const item of items) {
      if (item.id === target) {
        path.push(item)
        return true
      }
      if (item.children && search(item.children, target)) {
        path.unshift(item)
        return true
      }
    }
    return false
  }
  
  search(files, targetId)
  return path
}
