import type { FileItem, ImportJob, TrackImport } from "./types"

export const mockFileSystem: FileItem[] = [
  {
    id: "root",
    name: "Music Library",
    type: "folder",
    path: "/Music Library",
    parentId: null,
    children: [
      {
        id: "artist-1",
        name: "The Beatles",
        type: "folder",
        path: "/Music Library/The Beatles",
        parentId: "root",
        children: [
          {
            id: "album-1",
            name: "Abbey Road",
            type: "folder",
            path: "/Music Library/The Beatles/Abbey Road",
            parentId: "artist-1",
            children: [
              {
                id: "track-1",
                name: "Come Together.flac",
                type: "audio",
                path: "/Music Library/The Beatles/Abbey Road/Come Together.flac",
                parentId: "album-1",
                metadata: {
                  title: "Come Together",
                  artist: "The Beatles",
                  album: "Abbey Road",
                  year: 1969,
                  genre: "Rock",
                  duration: 259,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 45678912,
                  albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
                  lyrics: `Here come old flat top\nHe come grooving up slowly\nHe got joo joo eyeball\nHe one holy roller\nHe got hair down to his knee\nGot to be a joker, he just do what he please\n\nHe wear no shoeshine\nHe got toe-jam football\nHe got monkey finger\nHe shoot Coca-Cola\nHe say, "I know you, you know me"\nOne thing I can tell you is you got to be free\n\nCome together, right now\nOver me`,
                  fingerprint: "AQADtNIyRZIkSZEUJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: {
                    musicbrainz: true,
                    lastfm: true,
                    spotify: true,
                    genius: true,
                  },
                },
              },
              {
                id: "track-2",
                name: "Something.flac",
                type: "audio",
                path: "/Music Library/The Beatles/Abbey Road/Something.flac",
                parentId: "album-1",
                metadata: {
                  title: "Something",
                  artist: "The Beatles",
                  album: "Abbey Road",
                  year: 1969,
                  genre: "Rock",
                  duration: 182,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 32156789,
                  albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
                  fingerprint: "AQADtNIyRZIkTZEkJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: {
                    musicbrainz: true,
                    lastfm: true,
                    spotify: true,
                    genius: false,
                  },
                },
              },
              {
                id: "track-3",
                name: "Here Comes The Sun.flac",
                type: "audio",
                path: "/Music Library/The Beatles/Abbey Road/Here Comes The Sun.flac",
                parentId: "album-1",
                metadata: {
                  title: "Here Comes The Sun",
                  artist: "The Beatles",
                  album: "Abbey Road",
                  year: 1969,
                  genre: "Rock",
                  duration: 185,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 32678912,
                  albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
                  lyrics: `Here comes the sun, doo-doo-doo-doo\nHere comes the sun\nAnd I say, "It's all right"\n\nLittle darling, it's been a long cold lonely winter\nLittle darling, it feels like years since it's been here\n\nHere comes the sun\nHere comes the sun\nAnd I say, "It's all right"`,
                  fingerprint: "AQADtNIyRZIkSZEUSXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: {
                    musicbrainz: true,
                    lastfm: true,
                    spotify: true,
                    genius: true,
                  },
                },
              },
            ],
          },
          {
            id: "album-2",
            name: "Let It Be",
            type: "folder",
            path: "/Music Library/The Beatles/Let It Be",
            parentId: "artist-1",
            children: [
              {
                id: "track-4",
                name: "Let It Be.mp3",
                type: "audio",
                path: "/Music Library/The Beatles/Let It Be/Let It Be.mp3",
                parentId: "album-2",
                metadata: {
                  title: "Let It Be",
                  artist: "The Beatles",
                  album: "Let It Be",
                  year: 1970,
                  genre: "Rock",
                  duration: 243,
                  bitrate: 320,
                  sampleRate: 44100,
                  format: "MP3",
                  fileSize: 9756123,
                  albumArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
                  enrichmentStatus: "processing",
                  sources: {
                    musicbrainz: true,
                    lastfm: true,
                    spotify: false,
                    genius: false,
                  },
                },
              },
            ],
          },
        ],
      },
      {
        id: "artist-2",
        name: "Pink Floyd",
        type: "folder",
        path: "/Music Library/Pink Floyd",
        parentId: "root",
        children: [
          {
            id: "album-3",
            name: "The Dark Side of the Moon",
            type: "folder",
            path: "/Music Library/Pink Floyd/The Dark Side of the Moon",
            parentId: "artist-2",
            children: [
              {
                id: "track-5",
                name: "Time.flac",
                type: "audio",
                path: "/Music Library/Pink Floyd/The Dark Side of the Moon/Time.flac",
                parentId: "album-3",
                metadata: {
                  title: "Time",
                  artist: "Pink Floyd",
                  album: "The Dark Side of the Moon",
                  year: 1973,
                  genre: "Progressive Rock",
                  duration: 413,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 72891234,
                  albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
                  lyrics: `Ticking away the moments that make up a dull day\nFritter and waste the hours in an offhand way\nKicking around on a piece of ground in your hometown\nWaiting for someone or something to show you the way\n\nTired of lying in the sunshine, staying home to watch the rain\nYou are young and life is long, and there is time to kill today\nAnd then one day you find ten years have got behind you\nNo one told you when to run, you missed the starting gun`,
                  fingerprint: "BQBDtNIyRZIkSZEkJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: {
                    musicbrainz: true,
                    lastfm: true,
                    spotify: true,
                    genius: true,
                  },
                },
              },
              {
                id: "track-6",
                name: "Money.flac",
                type: "audio",
                path: "/Music Library/Pink Floyd/The Dark Side of the Moon/Money.flac",
                parentId: "album-3",
                metadata: {
                  title: "Money",
                  artist: "Pink Floyd",
                  album: "The Dark Side of the Moon",
                  year: 1973,
                  genre: "Progressive Rock",
                  duration: 382,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 67456789,
                  albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
                  fingerprint: "BQBDtNIyRZIkSZEkJXnO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: {
                    musicbrainz: true,
                    lastfm: true,
                    spotify: true,
                    genius: false,
                  },
                },
              },
              {
                id: "track-7",
                name: "Us and Them.flac",
                type: "audio",
                path: "/Music Library/Pink Floyd/The Dark Side of the Moon/Us and Them.flac",
                parentId: "album-3",
                metadata: {
                  title: "Us and Them",
                  artist: "Pink Floyd",
                  album: "The Dark Side of the Moon",
                  year: 1973,
                  genre: "Progressive Rock",
                  duration: 469,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 82789456,
                  albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
                  enrichmentStatus: "pending",
                  sources: {
                    musicbrainz: false,
                    lastfm: false,
                    spotify: false,
                    genius: false,
                  },
                },
              },
            ],
          },
        ],
      },
      {
        id: "artist-3",
        name: "Daft Punk",
        type: "folder",
        path: "/Music Library/Daft Punk",
        parentId: "root",
        children: [
          {
            id: "album-4",
            name: "Random Access Memories",
            type: "folder",
            path: "/Music Library/Daft Punk/Random Access Memories",
            parentId: "artist-3",
            children: [
              {
                id: "track-8",
                name: "Get Lucky.flac",
                type: "audio",
                path: "/Music Library/Daft Punk/Random Access Memories/Get Lucky.flac",
                parentId: "album-4",
                metadata: {
                  title: "Get Lucky",
                  artist: "Daft Punk ft. Pharrell Williams",
                  album: "Random Access Memories",
                  year: 2013,
                  genre: "Electronic",
                  duration: 369,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 65123456,
                  albumArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
                  lyrics: `Like the legend of the phoenix\nAll ends with beginnings\nWhat keeps the planet spinning\nThe force from the beginning\n\nWe've come too far to give up who we are\nSo let's raise the bar and our cups to the stars\n\nShe's up all night 'til the sun\nI'm up all night to get some\nShe's up all night for good fun\nI'm up all night to get lucky`,
                  fingerprint: "CQCDtNIyRZIkSZEkJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: {
                    musicbrainz: true,
                    lastfm: true,
                    spotify: true,
                    genius: true,
                  },
                },
              },
              {
                id: "track-9",
                name: "Instant Crush.flac",
                type: "audio",
                path: "/Music Library/Daft Punk/Random Access Memories/Instant Crush.flac",
                parentId: "album-4",
                metadata: {
                  title: "Instant Crush",
                  artist: "Daft Punk ft. Julian Casablancas",
                  album: "Random Access Memories",
                  year: 2013,
                  genre: "Electronic",
                  duration: 337,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 59456789,
                  albumArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
                  enrichmentStatus: "failed",
                  sources: {
                    musicbrainz: true,
                    lastfm: false,
                    spotify: false,
                    genius: false,
                  },
                },
              },
            ],
          },
        ],
      },
      {
        id: "artist-4",
        name: "Radiohead",
        type: "folder",
        path: "/Music Library/Radiohead",
        parentId: "root",
        children: [
          {
            id: "album-5",
            name: "OK Computer",
            type: "folder",
            path: "/Music Library/Radiohead/OK Computer",
            parentId: "artist-4",
            children: [
              {
                id: "track-10",
                name: "Paranoid Android.flac",
                type: "audio",
                path: "/Music Library/Radiohead/OK Computer/Paranoid Android.flac",
                parentId: "album-5",
                metadata: {
                  title: "Paranoid Android",
                  artist: "Radiohead",
                  album: "OK Computer",
                  year: 1997,
                  genre: "Alternative Rock",
                  duration: 386,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 68123456,
                  albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
                  enrichmentStatus: "complete",
                  sources: {
                    musicbrainz: true,
                    lastfm: true,
                    spotify: true,
                    genius: true,
                  },
                },
              },
              {
                id: "track-11",
                name: "Karma Police.flac",
                type: "audio",
                path: "/Music Library/Radiohead/OK Computer/Karma Police.flac",
                parentId: "album-5",
                metadata: {
                  title: "Karma Police",
                  artist: "Radiohead",
                  album: "OK Computer",
                  year: 1997,
                  genre: "Alternative Rock",
                  duration: 264,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 46567890,
                  albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
                  lyrics: `Karma police, arrest this man\nHe talks in maths, he buzzes like a fridge\nHe's like a detuned radio\n\nKarma police, arrest this girl\nHer Hitler hairdo is making me feel ill\nAnd we have crashed her party\n\nThis is what you get\nThis is what you get\nThis is what you get\nWhen you mess with us`,
                  fingerprint: "DQDDtNIyRZIkSZEkJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: {
                    musicbrainz: true,
                    lastfm: true,
                    spotify: true,
                    genius: true,
                  },
                },
              },
            ],
          },
        ],
      },
      {
        id: "unsorted",
        name: "Unsorted",
        type: "folder",
        path: "/Music Library/Unsorted",
        parentId: "root",
        children: [
          {
            id: "track-12",
            name: "unknown_track_001.mp3",
            type: "audio",
            path: "/Music Library/Unsorted/unknown_track_001.mp3",
            parentId: "unsorted",
            metadata: {
              title: "Unknown Track",
              artist: "Unknown Artist",
              album: "Unknown Album",
              year: 0,
              genre: "Unknown",
              duration: 234,
              bitrate: 192,
              sampleRate: 44100,
              format: "MP3",
              fileSize: 5623456,
              enrichmentStatus: "pending",
              sources: {
                musicbrainz: false,
                lastfm: false,
                spotify: false,
                genius: false,
              },
            },
          },
          {
            id: "track-13",
            name: "mystery_song.wav",
            type: "audio",
            path: "/Music Library/Unsorted/mystery_song.wav",
            parentId: "unsorted",
            metadata: {
              title: "Mystery Song",
              artist: "Unknown",
              album: "Unknown",
              year: 0,
              genre: "Unknown",
              duration: 198,
              bitrate: 1411,
              sampleRate: 44100,
              format: "WAV",
              fileSize: 34891234,
              enrichmentStatus: "processing",
              sources: {
                musicbrainz: false,
                lastfm: false,
                spotify: false,
                genius: false,
              },
            },
          },
        ],
      },
    ],
  },
]

export const mockImportJob: ImportJob = {
  id: "job-1",
  sourcePath: "/Volumes/External/Music Import",
  destinationPath: "/Music Library",
  status: "running",
  startedAt: new Date(Date.now() - 1000 * 60 * 45), // 45 mins ago
  tracksDiscovered: 847,
  tracksProcessed: 623,
  tracksCopied: 589,
  tracksReview: 18,
  tracksFailed: 16,
}

export const mockTracksForReview: TrackImport[] = [
  {
    id: "review-1",
    originalPath: "/Volumes/External/Music Import/Unknown/track01.mp3",
    status: "review",
    metadata: {
      title: "Track 01",
      artist: "Unknown Artist",
      album: "Unknown Album",
      year: 0,
      genre: "Unknown",
      duration: 234,
      bitrate: 320,
      sampleRate: 44100,
      format: "MP3",
      fileSize: 9345678,
      enrichmentStatus: "complete",
      sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
    },
    suggestedMetadata: {
      title: "Bohemian Rhapsody",
      artist: "Queen",
      album: "A Night at the Opera",
      year: 1975,
      genre: "Rock",
      albumArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    },
    issues: ["Low confidence match (67%)", "Multiple potential matches found"],
    fingerprint: "AQADtNIyRZIkSZEkJXmO44iS5DiO",
  },
  {
    id: "review-2",
    originalPath: "/Volumes/External/Music Import/Downloads/song.flac",
    status: "review",
    metadata: {
      title: "song",
      artist: "Unknown",
      album: "Unknown",
      year: 0,
      genre: "Unknown",
      duration: 312,
      bitrate: 1411,
      sampleRate: 44100,
      format: "FLAC",
      fileSize: 55123456,
      enrichmentStatus: "complete",
      sources: { musicbrainz: true, lastfm: false, spotify: false, genius: false },
    },
    suggestedMetadata: {
      title: "Stairway to Heaven",
      artist: "Led Zeppelin",
      album: "Led Zeppelin IV",
      year: 1971,
      genre: "Rock",
      albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    },
    issues: ["Metadata mismatch with filename"],
    fingerprint: "BQBDtNIyRZIkSZEkJXmO44iS5DiO",
  },
  {
    id: "review-3",
    originalPath: "/Volumes/External/Music Import/CDs/Disc1/03.wav",
    status: "review",
    metadata: {
      title: "03",
      artist: "Unknown",
      album: "Disc1",
      year: 0,
      genre: "Unknown",
      duration: 267,
      bitrate: 1411,
      sampleRate: 44100,
      format: "WAV",
      fileSize: 47123456,
      enrichmentStatus: "complete",
      sources: { musicbrainz: true, lastfm: true, spotify: false, genius: false },
    },
    suggestedMetadata: {
      title: "Hotel California",
      artist: "Eagles",
      album: "Hotel California",
      year: 1977,
      genre: "Rock",
      albumArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
    },
    issues: ["No embedded metadata", "Confidence: 89%"],
    fingerprint: "CQCDtNIyRZIkSZEkJXmO44iS5DiO",
  },
  {
    id: "review-4",
    originalPath: "/Volumes/External/Music Import/Rips/album/track_04.flac",
    status: "review",
    metadata: {
      title: "Track 4",
      artist: "Various Artists",
      album: "Compilation",
      year: 2020,
      genre: "Pop",
      duration: 198,
      bitrate: 1411,
      sampleRate: 44100,
      format: "FLAC",
      fileSize: 35000000,
      enrichmentStatus: "complete",
      sources: { musicbrainz: false, lastfm: false, spotify: true, genius: false },
    },
    suggestedMetadata: {
      title: "Billie Jean",
      artist: "Michael Jackson",
      album: "Thriller",
      year: 1982,
      genre: "Pop",
      albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
    },
    issues: ["Existing metadata conflicts with fingerprint match"],
    fingerprint: "DQDDtNIyRZIkSZEkJXmO44iS5DiO",
  },
  {
    id: "review-5",
    originalPath: "/Volumes/External/Music Import/New/untitled.mp3",
    status: "review",
    metadata: {
      title: "Untitled",
      artist: "",
      album: "",
      year: 0,
      genre: "Unknown",
      duration: 245,
      bitrate: 256,
      sampleRate: 44100,
      format: "MP3",
      fileSize: 7800000,
      enrichmentStatus: "failed",
      sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
    },
    issues: ["No fingerprint match found", "Manual entry required"],
    fingerprint: undefined,
  },
  {
    id: "review-6",
    originalPath: "/Volumes/External/Music Import/Archive/old_recording.wav",
    status: "review",
    metadata: {
      title: "Old Recording",
      artist: "Home Recording",
      album: "Personal",
      year: 1995,
      genre: "Unknown",
      duration: 356,
      bitrate: 1411,
      sampleRate: 44100,
      format: "WAV",
      fileSize: 62000000,
      enrichmentStatus: "complete",
      sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
    },
    suggestedMetadata: {
      title: "Wish You Were Here",
      artist: "Pink Floyd",
      album: "Wish You Were Here",
      year: 1975,
      genre: "Progressive Rock",
      albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    },
    issues: ["Low audio quality detected", "Possible live recording"],
    fingerprint: "EQEDtNIyRZIkSZEkJXmO44iS5DiO",
  },
]

export const mockRecentActivity = [
  { id: "act-1", type: "discovered" as const, track: "Come Together.flac", artist: "The Beatles", time: "2 min ago" },
  { id: "act-2", type: "copied" as const, track: "Something.flac", artist: "The Beatles", time: "3 min ago" },
  { id: "act-3", type: "enriched" as const, track: "Here Comes The Sun.flac", artist: "The Beatles", time: "5 min ago" },
  { id: "act-4", type: "review" as const, track: "unknown_track.mp3", artist: "Unknown", time: "6 min ago" },
  { id: "act-5", type: "copied" as const, track: "Time.flac", artist: "Pink Floyd", time: "8 min ago" },
  { id: "act-6", type: "failed" as const, track: "corrupted_file.mp3", artist: "Unknown", time: "10 min ago" },
  { id: "act-7", type: "discovered" as const, track: "Money.flac", artist: "Pink Floyd", time: "12 min ago" },
  { id: "act-8", type: "enriched" as const, track: "Get Lucky.flac", artist: "Daft Punk", time: "15 min ago" },
]

export function findFileById(files: FileItem[], id: string): FileItem | null {
  for (const file of files) {
    if (file.id === id) return file
    if (file.children) {
      const found = findFileById(file.children, id)
      if (found) return found
    }
  }
  return null
}

export function getPathToFile(files: FileItem[], targetId: string): FileItem[] {
  const path: FileItem[] = []
  
  function search(items: FileItem[], target: string): boolean {
    for (const item of items) {
      if (item.id === target) {
        path.push(item)
        return true
      }
      if (item.children && search(item.children, target)) {
        path.unshift(item)
        return true
      }
    }
    return false
  }
  
  search(files, targetId)
  return path
}
