import type { FileItem, ImportJob, TrackImport, Artist, DiscographyAlbum, SpotifyPlaylist, SpotifyTrack } from "./types"

const SOURCE_ROOT = "/Volumes/music"

export const mockFileSystem: FileItem[] = [
  {
    id: "root",
    name: "music",
    type: "folder",
    path: SOURCE_ROOT,
    parentId: null,
    children: [
      // Messy: CD Rips with generic filenames
      {
        id: "folder-cdrips",
        name: "CD Rips",
        type: "folder",
        path: `${SOURCE_ROOT}/CD Rips`,
        parentId: "root",
        children: [
          {
            id: "folder-disc1",
            name: "Disc1",
            type: "folder",
            path: `${SOURCE_ROOT}/CD Rips/Disc1`,
            parentId: "folder-cdrips",
            children: [
              {
                id: "track-cd1",
                name: "01 - unknown.wav",
                type: "audio",
                path: `${SOURCE_ROOT}/CD Rips/Disc1/01 - unknown.wav`,
                parentId: "folder-disc1",
                metadata: {
                  title: "Track 01",
                  artist: "Unknown Artist",
                  album: "Disc1",
                  year: 0,
                  genre: "Unknown",
                  duration: 245,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "WAV",
                  fileSize: 41234567,
                  lyricsStatus: "NotFound" as const,
                  hasSyncedLyrics: false,
                  hasPlainLyrics: false,
                  enrichmentStatus: "pending",
                  sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
                },
              },
              {
                id: "track-cd2",
                name: "02 - track.wav",
                type: "audio",
                path: `${SOURCE_ROOT}/CD Rips/Disc1/02 - track.wav`,
                parentId: "folder-disc1",
                metadata: {
                  title: "Track 02",
                  artist: "Unknown Artist",
                  album: "Disc1",
                  year: 0,
                  genre: "Unknown",
                  duration: 198,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "WAV",
                  fileSize: 33456789,
                  lyricsStatus: "NotFound" as const,
                  hasSyncedLyrics: false,
                  hasPlainLyrics: false,
                  enrichmentStatus: "pending",
                  sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
                },
              },
            ],
          },
        ],
      },
      // Messy: Downloads with date subfolder
      {
        id: "folder-downloads",
        name: "Downloads",
        type: "folder",
        path: `${SOURCE_ROOT}/Downloads`,
        parentId: "root",
        children: [
          {
            id: "folder-2020-03",
            name: "2020-03",
            type: "folder",
            path: `${SOURCE_ROOT}/Downloads/2020-03`,
            parentId: "folder-downloads",
            children: [
              {
                id: "track-dl1",
                name: "random_song.mp3",
                type: "audio",
                path: `${SOURCE_ROOT}/Downloads/2020-03/random_song.mp3`,
                parentId: "folder-2020-03",
                metadata: {
                  title: "Random Song",
                  artist: "Various Artists",
                  album: "Unknown",
                  year: 2020,
                  genre: "Pop",
                  duration: 223,
                  bitrate: 256,
                  sampleRate: 44100,
                  format: "MP3",
                  fileSize: 7123456,
                  syncedLyrics: `[00:12.00] We could be strangers in the night\n[00:16.50] Or we could be something more\n[00:21.00] Random song on the radio\n[00:25.50] Playing like never before\n[00:30.00] \n[00:31.20] So turn it up and let it go\n[00:35.70] Feel the beat and lose control`,
                  plainLyrics: `We could be strangers in the night\nOr we could be something more\nRandom song on the radio\nPlaying like never before\n\nSo turn it up and let it go\nFeel the beat and lose control`,
                  lyrics: `[00:12.00] We could be strangers in the night\n[00:16.50] Or we could be something more\n[00:21.00] Random song on the radio`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: false, spotify: true, genius: false },
                },
              },
            ],
          },
        ],
      },
      // The Beatles – partly organized, with messy duplicate folder
      {
        id: "artist-1",
        name: "The Beatles",
        type: "folder",
        path: `${SOURCE_ROOT}/The Beatles`,
        parentId: "root",
        children: [
          {
            id: "album-1",
            name: "Abbey Road",
            type: "folder",
            path: `${SOURCE_ROOT}/The Beatles/Abbey Road`,
            parentId: "artist-1",
            children: [
              {
                id: "track-1",
                name: "Come Together.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/The Beatles/Abbey Road/Come Together.flac`,
                parentId: "album-1",
                metadata: {
                  title: "Come Together",
                  artist: "The Beatles",
                  album: "Abbey Road",
                  year: 1969,
                  genre: "Rock",
                  duration: 259,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 45678912,
                  albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:00.00] \n[00:21.30] Here come old flat top\n[00:24.10] He come grooving up slowly\n[00:27.20] He got joo joo eyeball\n[00:30.40] He one holy roller\n[00:33.60] He got hair down to his knee\n[00:36.80] Got to be a joker, he just do what he please\n[00:43.10] \n[00:44.50] He wear no shoeshine\n[00:47.30] He got toe-jam football\n[00:50.20] He got monkey finger\n[00:53.10] He shoot Coca-Cola\n[00:56.20] He say, "I know you, you know me"\n[00:59.40] One thing I can tell you is you got to be free\n[01:02.60] \n[01:03.80] Come together, right now\n[01:07.10] Over me`,
                  plainLyrics: `Here come old flat top\nHe come grooving up slowly\nHe got joo joo eyeball\nHe one holy roller\nHe got hair down to his knee\nGot to be a joker, he just do what he please\n\nHe wear no shoeshine\nHe got toe-jam football\nHe got monkey finger\nHe shoot Coca-Cola\nHe say, "I know you, you know me"\nOne thing I can tell you is you got to be free\n\nCome together, right now\nOver me`,
                  lyrics: `[00:00.00] \n[00:21.30] Here come old flat top\n[00:24.10] He come grooving up slowly\n[00:27.20] He got joo joo eyeball\n[00:30.40] He one holy roller\n[00:33.60] He got hair down to his knee\n[00:36.80] Got to be a joker, he just do what he please\n[00:43.10] \n[00:44.50] He wear no shoeshine\n[00:47.30] He got toe-jam football\n[00:50.20] He got monkey finger\n[00:53.10] He shoot Coca-Cola\n[00:56.20] He say, "I know you, you know me"\n[00:59.40] One thing I can tell you is you got to be free\n[01:02.60] \n[01:03.80] Come together, right now\n[01:07.10] Over me`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  fingerprint: "AQADtNIyRZIkSZEUJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-2",
                name: "Something.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/The Beatles/Abbey Road/Something.flac`,
                parentId: "album-1",
                metadata: {
                  title: "Something",
                  artist: "The Beatles",
                  album: "Abbey Road",
                  year: 1969,
                  genre: "Rock",
                  duration: 182,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 32156789,
                  albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:03.10] Something in the way she moves\n[00:06.80] Attracts me like no other lover\n[00:10.50] Something in the way she woos me\n[00:14.20] I don't want to leave her now\n[00:17.90] You know I believe and how\n[00:25.40] \n[00:26.10] Somewhere in her smile she knows\n[00:29.80] That I don't need no other lover\n[00:33.50] Something in her style that shows me\n[00:37.20] I don't want to leave her now\n[00:40.90] You know I believe and how`,
                  plainLyrics: `Something in the way she moves\nAttracts me like no other lover\nSomething in the way she woos me\nI don't want to leave her now\nYou know I believe and how\n\nSomewhere in her smile she knows\nThat I don't need no other lover\nSomething in her style that shows me\nI don't want to leave her now\nYou know I believe and how`,
                  lyrics: `[00:03.10] Something in the way she moves\n[00:06.80] Attracts me like no other lover\n[00:10.50] Something in the way she woos me\n[00:14.20] I don't want to leave her now\n[00:17.90] You know I believe and how`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  fingerprint: "AQADtNIyRZIkTZEkJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: false },
                },
              },
              {
                id: "track-3",
                name: "Here Comes The Sun.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/The Beatles/Abbey Road/Here Comes The Sun.flac`,
                parentId: "album-1",
                metadata: {
                  title: "Here Comes The Sun",
                  artist: "The Beatles",
                  album: "Abbey Road",
                  year: 1969,
                  genre: "Rock",
                  duration: 185,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 32678912,
                  albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:07.00] Here comes the sun, doo-doo-doo-doo\n[00:10.20] Here comes the sun\n[00:13.00] And I say, "It's all right"\n[00:20.50] \n[00:21.80] Little darling, it's been a long cold lonely winter\n[00:27.30] Little darling, it feels like years since it's been here\n[00:33.10] \n[00:34.40] Here comes the sun\n[00:37.20] Here comes the sun\n[00:40.10] And I say, "It's all right"`,
                  plainLyrics: `Here comes the sun, doo-doo-doo-doo\nHere comes the sun\nAnd I say, "It's all right"\n\nLittle darling, it's been a long cold lonely winter\nLittle darling, it feels like years since it's been here\n\nHere comes the sun\nHere comes the sun\nAnd I say, "It's all right"`,
                  lyrics: `[00:07.00] Here comes the sun, doo-doo-doo-doo\n[00:10.20] Here comes the sun\n[00:13.00] And I say, "It's all right"\n[00:20.50] \n[00:21.80] Little darling, it's been a long cold lonely winter\n[00:27.30] Little darling, it feels like years since it's been here`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  fingerprint: "AQADtNIyRZIkSZEUSXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
            ],
          },
          {
            id: "album-2",
            name: "Let It Be",
            type: "folder",
            path: `${SOURCE_ROOT}/The Beatles/Let It Be`,
            parentId: "artist-1",
            children: [
              {
                id: "track-4",
                name: "Let It Be.mp3",
                type: "audio",
                path: `${SOURCE_ROOT}/The Beatles/Let It Be/Let It Be.mp3`,
                parentId: "album-2",
                metadata: {
                  title: "Let It Be",
                  artist: "The Beatles",
                  album: "Let It Be",
                  year: 1970,
                  genre: "Rock",
                  duration: 243,
                  bitrate: 320,
                  sampleRate: 44100,
                  format: "MP3",
                  fileSize: 9756123,
                  albumArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:00.00] When I find myself in times of trouble\n[00:05.20] Mother Mary comes to me\n[00:09.80] Speaking words of wisdom, let it be\n[00:18.40] And in my hour of darkness\n[00:22.90] She is standing right in front of me\n[00:27.50] Speaking words of wisdom, let it be\n[00:36.10] Let it be, let it be\n[00:40.60] Let it be, let it be\n[00:45.20] Whisper words of wisdom, let it be`,
                  plainLyrics: `When I find myself in times of trouble\nMother Mary comes to me\nSpeaking words of wisdom, let it be\nAnd in my hour of darkness\nShe is standing right in front of me\nSpeaking words of wisdom, let it be\nLet it be, let it be\nLet it be, let it be\nWhisper words of wisdom, let it be`,
                  lyrics: `[00:00.00] When I find myself in times of trouble\n[00:05.20] Mother Mary comes to me\n[00:09.80] Speaking words of wisdom, let it be`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "processing",
                  sources: { musicbrainz: true, lastfm: true, spotify: false, genius: false },
                },
              },
            ],
          },
          // Messy: duplicate-style folder with one stray
          {
            id: "album-1-dup",
            name: "Abbey Road (1)",
            type: "folder",
            path: `${SOURCE_ROOT}/The Beatles/Abbey Road (1)`,
            parentId: "artist-1",
            children: [
              {
                id: "track-3-dup",
                name: "Here Comes The Sun.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/The Beatles/Abbey Road (1)/Here Comes The Sun.flac`,
                parentId: "album-1-dup",
                metadata: {
                  title: "Here Comes The Sun",
                  artist: "The Beatles",
                  album: "Abbey Road",
                  year: 1969,
                  genre: "Rock",
                  duration: 185,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 32678912,
                  albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:07.00] Here comes the sun, doo-doo-doo-doo\n[00:10.20] Here comes the sun\n[00:13.00] And I say, "It's all right"\n[00:20.50] \n[00:21.80] Little darling, it's been a long cold lonely winter\n[00:27.30] Little darling, it feels like years since it's been here\n[00:33.10] \n[00:34.40] Here comes the sun\n[00:37.20] Here comes the sun\n[00:40.10] And I say, "It's all right"`,
                  plainLyrics: `Here comes the sun, doo-doo-doo-doo\nHere comes the sun\nAnd I say, "It's all right"\n\nLittle darling, it's been a long cold lonely winter\nLittle darling, it feels like years since it's been here\n\nHere comes the sun\nHere comes the sun\nAnd I say, "It's all right"`,
                  lyrics: `[00:07.00] Here comes the sun, doo-doo-doo-doo\n[00:10.20] Here comes the sun\n[00:13.00] And I say, "It's all right"`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
            ],
          },
        ],
      },
      // Pink Floyd – album folder + loose file at artist level
      {
        id: "artist-2",
        name: "Pink Floyd",
        type: "folder",
        path: `${SOURCE_ROOT}/Pink Floyd`,
        parentId: "root",
        children: [
              {
                id: "track-5-loose",
                name: "time_backup.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Pink Floyd/time_backup.flac`,
                parentId: "artist-2",
                metadata: {
                  title: "Time",
                  artist: "Pink Floyd",
                  album: "The Dark Side of the Moon",
                  year: 1973,
                  genre: "Progressive Rock",
                  duration: 413,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 72891234,
                  albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
                  fingerprint: "BQBDtNIyRZIkSZEkJXmO44iS5DiO",
                  syncedLyrics: `[00:30.00] Ticking away the moments that make up a dull day\n[00:35.40] Fritter and waste the hours in an offhand way\n[00:40.80] Kicking around on a piece of ground in your hometown\n[00:46.20] Waiting for someone or something to show you the way`,
                  plainLyrics: `Ticking away the moments that make up a dull day\nFritter and waste the hours in an offhand way\nKicking around on a piece of ground in your hometown\nWaiting for someone or something to show you the way`,
                  lyrics: `[00:30.00] Ticking away the moments that make up a dull day\n[00:35.40] Fritter and waste the hours in an offhand way`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
          {
            id: "album-3",
            name: "The Dark Side of the Moon",
            type: "folder",
            path: `${SOURCE_ROOT}/Pink Floyd/The Dark Side of the Moon`,
            parentId: "artist-2",
            children: [
              {
                id: "track-5",
                name: "Time.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Pink Floyd/The Dark Side of the Moon/Time.flac`,
                parentId: "album-3",
                metadata: {
                  title: "Time",
                  artist: "Pink Floyd",
                  album: "The Dark Side of the Moon",
                  year: 1973,
                  genre: "Progressive Rock",
                  duration: 413,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 72891234,
                  albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:30.00] Ticking away the moments that make up a dull day\n[00:35.40] Fritter and waste the hours in an offhand way\n[00:40.80] Kicking around on a piece of ground in your hometown\n[00:46.20] Waiting for someone or something to show you the way\n[00:52.00] \n[00:53.40] Tired of lying in the sunshine, staying home to watch the rain\n[00:59.10] You are young and life is long, and there is time to kill today\n[01:04.60] And then one day you find ten years have got behind you\n[01:10.00] No one told you when to run, you missed the starting gun`,
                  plainLyrics: `Ticking away the moments that make up a dull day\nFritter and waste the hours in an offhand way\nKicking around on a piece of ground in your hometown\nWaiting for someone or something to show you the way\n\nTired of lying in the sunshine, staying home to watch the rain\nYou are young and life is long, and there is time to kill today\nAnd then one day you find ten years have got behind you\nNo one told you when to run, you missed the starting gun`,
                  lyrics: `[00:30.00] Ticking away the moments that make up a dull day\n[00:35.40] Fritter and waste the hours in an offhand way\n[00:40.80] Kicking around on a piece of ground in your hometown\n[00:46.20] Waiting for someone or something to show you the way`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  fingerprint: "BQBDtNIyRZIkSZEkJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-6",
                name: "Money.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Pink Floyd/The Dark Side of the Moon/Money.flac`,
                parentId: "album-3",
                metadata: {
                  title: "Money",
                  artist: "Pink Floyd",
                  album: "The Dark Side of the Moon",
                  year: 1973,
                  genre: "Progressive Rock",
                  duration: 382,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 67456789,
                  albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
                  fingerprint: "BQBDtNIyRZIkSZEkJXnO44iS5DiO",
                  syncedLyrics: `[00:00.50] Money, get away\n[00:04.20] Get a good job with more pay and you're okay\n[00:11.90] Money, it's a gas\n[00:15.60] Grab that cash with both hands and make a stash\n[00:23.30] New car, caviar, four star daydream\n[00:30.90] Think I'll buy me a football team`,
                  plainLyrics: `Money, get away\nGet a good job with more pay and you're okay\nMoney, it's a gas\nGrab that cash with both hands and make a stash\nNew car, caviar, four star daydream\nThink I'll buy me a football team`,
                  lyrics: `[00:00.50] Money, get away\n[00:04.20] Get a good job with more pay and you're okay\n[00:11.90] Money, it's a gas`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: false },
                },
              },
              {
                id: "track-7",
                name: "Us and Them.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Pink Floyd/The Dark Side of the Moon/Us and Them.flac`,
                parentId: "album-3",
                metadata: {
                  title: "Us and Them",
                  artist: "Pink Floyd",
                  album: "The Dark Side of the Moon",
                  year: 1973,
                  genre: "Progressive Rock",
                  duration: 469,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 82789456,
                  albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:42.00] Us and them\n[00:48.50] And after all we're only ordinary men\n[00:55.00] Me and you\n[01:01.50] God only knows it's not what we would choose to do\n[01:08.00] \n[01:14.50] Forward he cried from the rear\n[01:21.00] And the front rank died\n[01:27.50] And the general sat and the lines on the map\n[01:34.00] moved from side to side`,
                  plainLyrics: `Us and them\nAnd after all we're only ordinary men\nMe and you\nGod only knows it's not what we would choose to do\n\nForward he cried from the rear\nAnd the front rank died\nAnd the general sat and the lines on the map\nmoved from side to side`,
                  lyrics: `[00:42.00] Us and them\n[00:48.50] And after all we're only ordinary men\n[00:55.00] Me and you`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "pending",
                  sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
                },
              },
            ],
          },
        ],
      },
      {
        id: "artist-3",
        name: "Daft Punk",
        type: "folder",
        path: `${SOURCE_ROOT}/Daft Punk`,
        parentId: "root",
        children: [
          {
            id: "album-4",
            name: "Random Access Memories",
            type: "folder",
            path: `${SOURCE_ROOT}/Daft Punk/Random Access Memories`,
            parentId: "artist-3",
            children: [
              {
                id: "track-8",
                name: "Get Lucky.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Daft Punk/Random Access Memories/Get Lucky.flac`,
                parentId: "album-4",
                metadata: {
                  title: "Get Lucky",
                  artist: "Daft Punk ft. Pharrell Williams",
                  album: "Random Access Memories",
                  year: 2013,
                  genre: "Electronic",
                  duration: 369,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 65123456,
                  albumArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:26.50] Like the legend of the phoenix\n[00:29.80] All ends with beginnings\n[00:33.10] What keeps the planet spinning\n[00:36.40] The force from the beginning\n[00:42.70] \n[00:43.90] We've come too far to give up who we are\n[00:47.20] So let's raise the bar and our cups to the stars\n[00:53.50] \n[00:54.80] She's up all night 'til the sun\n[00:58.10] I'm up all night to get some\n[01:01.40] She's up all night for good fun\n[01:04.70] I'm up all night to get lucky`,
                  plainLyrics: `Like the legend of the phoenix\nAll ends with beginnings\nWhat keeps the planet spinning\nThe force from the beginning\n\nWe've come too far to give up who we are\nSo let's raise the bar and our cups to the stars\n\nShe's up all night 'til the sun\nI'm up all night to get some\nShe's up all night for good fun\nI'm up all night to get lucky`,
                  lyrics: `[00:26.50] Like the legend of the phoenix\n[00:29.80] All ends with beginnings\n[00:33.10] What keeps the planet spinning\n[00:36.40] The force from the beginning\n[00:42.70] \n[00:43.90] We've come too far to give up who we are\n[00:47.20] So let's raise the bar and our cups to the stars`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  fingerprint: "CQCDtNIyRZIkSZEkJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-9",
                name: "Instant Crush.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Daft Punk/Random Access Memories/Instant Crush.flac`,
                parentId: "album-4",
                metadata: {
                  title: "Instant Crush",
                  artist: "Daft Punk ft. Julian Casablancas",
                  album: "Random Access Memories",
                  year: 2013,
                  genre: "Electronic",
                  duration: 337,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 59456789,
                  albumArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:18.00] I didn't want to be the one to forget\n[00:22.50] I thought of everything I'd never regret\n[00:27.00] A little time with you is all I need\n[00:31.50] A little time with you is all I need\n[00:36.00] \n[00:40.50] We stayed up all night\n[00:45.00] I don't know how or why\n[00:49.50] I'll do anything you ask me to\n[00:54.00] But I can't do it with you`,
                  plainLyrics: `I didn't want to be the one to forget\nI thought of everything I'd never regret\nA little time with you is all I need\nA little time with you is all I need\n\nWe stayed up all night\nI don't know how or why\nI'll do anything you ask me to\nBut I can't do it with you`,
                  lyrics: `[00:18.00] I didn't want to be the one to forget\n[00:22.50] I thought of everything I'd never regret\n[00:27.00] A little time with you is all I need`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "failed",
                  sources: { musicbrainz: true, lastfm: false, spotify: false, genius: false },
                },
              },
            ],
          },
        ],
      },
      {
        id: "artist-4",
        name: "Radiohead",
        type: "folder",
        path: `${SOURCE_ROOT}/Radiohead`,
        parentId: "root",
        children: [
          {
            id: "album-5",
            name: "OK Computer",
            type: "folder",
            path: `${SOURCE_ROOT}/Radiohead/OK Computer`,
            parentId: "artist-4",
            children: [
              {
                id: "track-10",
                name: "Paranoid Android.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Radiohead/OK Computer/Paranoid Android.flac`,
                parentId: "album-5",
                metadata: {
                  title: "Paranoid Android",
                  artist: "Radiohead",
                  album: "OK Computer",
                  year: 1997,
                  genre: "Alternative Rock",
                  duration: 386,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 68123456,
                  albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:00.00] Please could you stop the noise, I'm trying to get some rest\n[00:06.50] From all the unborn chicken voices in my head\n[00:13.00] What's that? (I may be paranoid, but not an android)\n[00:19.50] What's that? (I may be paranoid, but not an android)\n[00:26.00] \n[00:39.00] When I am king, you will be first against the wall\n[00:45.50] With your opinion which is of no consequence at all`,
                  plainLyrics: `Please could you stop the noise, I'm trying to get some rest\nFrom all the unborn chicken voices in my head\nWhat's that? (I may be paranoid, but not an android)\nWhen I am king, you will be first against the wall\nWith your opinion which is of no consequence at all`,
                  lyrics: `[00:00.00] Please could you stop the noise, I'm trying to get some rest\n[00:06.50] From all the unborn chicken voices in my head`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-11",
                name: "Karma Police.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Radiohead/OK Computer/Karma Police.flac`,
                parentId: "album-5",
                metadata: {
                  title: "Karma Police",
                  artist: "Radiohead",
                  album: "OK Computer",
                  year: 1997,
                  genre: "Alternative Rock",
                  duration: 264,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 46567890,
                  albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:15.00] Karma police, arrest this man\n[00:18.60] He talks in maths, he buzzes like a fridge\n[00:22.30] He's like a detuned radio\n[00:29.10] \n[00:30.40] Karma police, arrest this girl\n[00:34.10] Her Hitler hairdo is making me feel ill\n[00:37.80] And we have crashed her party\n[00:44.50] \n[00:45.80] This is what you get\n[00:49.30] This is what you get\n[00:52.80] This is what you get\n[00:56.30] When you mess with us`,
                  plainLyrics: `Karma police, arrest this man\nHe talks in maths, he buzzes like a fridge\nHe's like a detuned radio\n\nKarma police, arrest this girl\nHer Hitler hairdo is making me feel ill\nAnd we have crashed her party\n\nThis is what you get\nThis is what you get\nThis is what you get\nWhen you mess with us`,
                  lyrics: `[00:15.00] Karma police, arrest this man\n[00:18.60] He talks in maths, he buzzes like a fridge\n[00:22.30] He's like a detuned radio\n[00:29.10] \n[00:30.40] Karma police, arrest this girl\n[00:34.10] Her Hitler hairdo is making me feel ill\n[00:37.80] And we have crashed her party`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  fingerprint: "DQDDtNIyRZIkSZEkJXmO44iS5DiO",
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
            ],
          },
        ],
      },
      // Messy: inconsistent naming
      {
        id: "artist-1-alt",
        name: "the beatles",
        type: "folder",
        path: `${SOURCE_ROOT}/the beatles`,
        parentId: "root",
        children: [
          {
            id: "album-2-alt",
            name: "let it be",
            type: "folder",
            path: `${SOURCE_ROOT}/the beatles/let it be`,
            parentId: "artist-1-alt",
            children: [
              {
                id: "track-4-alt",
                name: "get back.mp3",
                type: "audio",
                path: `${SOURCE_ROOT}/the beatles/let it be/get back.mp3`,
                parentId: "album-2-alt",
                metadata: {
                  title: "Get Back",
                  artist: "The Beatles",
                  album: "Let It Be",
                  year: 1970,
                  genre: "Rock",
                  duration: 191,
                  bitrate: 320,
                  sampleRate: 44100,
                  format: "MP3",
                  fileSize: 7654321,
                  albumArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:00.00] Jojo was a man who thought he was a loner\n[00:04.50] But he knew it couldn't last\n[00:09.00] Jojo left his home in Tucson, Arizona\n[00:13.50] For some California grass\n[00:18.00] Get back, get back\n[00:22.50] Get back to where you once belonged\n[00:27.00] Get back, get back\n[00:31.50] Get back to where you once belonged`,
                  plainLyrics: `Jojo was a man who thought he was a loner\nBut he knew it couldn't last\nJojo left his home in Tucson, Arizona\nFor some California grass\nGet back, get back\nGet back to where you once belonged`,
                  lyrics: `[00:00.00] Jojo was a man who thought he was a loner\n[00:04.50] But he knew it couldn't last\n[00:09.00] Jojo left his home in Tucson, Arizona`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: false },
                },
              },
            ],
          },
        ],
      },
      // New artists: Fleetwood Mac, Nirvana, David Bowie
      {
        id: "artist-5",
        name: "Fleetwood Mac",
        type: "folder",
        path: `${SOURCE_ROOT}/Fleetwood Mac`,
        parentId: "root",
        children: [
          {
            id: "album-6",
            name: "Rumours",
            type: "folder",
            path: `${SOURCE_ROOT}/Fleetwood Mac/Rumours`,
            parentId: "artist-5",
            children: [
              {
                id: "track-fm1",
                name: "Go Your Own Way.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Fleetwood Mac/Rumours/Go Your Own Way.flac`,
                parentId: "album-6",
                metadata: {
                  title: "Go Your Own Way",
                  artist: "Fleetwood Mac",
                  album: "Rumours",
                  year: 1977,
                  genre: "Rock",
                  duration: 214,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 37891234,
                  albumArt: "https://images.unsplash.com/photo-1484755560615-a4c64e778a6c?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:00.00] Loving you isn't the right thing to do\n[00:05.20] How can I ever change things that I feel?\n[00:10.40] If I could maybe I'd give you my world\n[00:15.60] How can I when you won't take it from me?\n[00:20.80] You can go your own way\n[00:25.00] Go your own way\n[00:29.20] You can call it another lonely day`,
                  plainLyrics: `Loving you isn't the right thing to do\nHow can I ever change things that I feel?\nIf I could maybe I'd give you my world\nHow can I when you won't take it from me?\nYou can go your own way\nGo your own way\nYou can call it another lonely day`,
                  lyrics: `[00:00.00] Loving you isn't the right thing to do\n[00:05.20] How can I ever change things that I feel?`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-fm2",
                name: "Dreams.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Fleetwood Mac/Rumours/Dreams.flac`,
                parentId: "album-6",
                metadata: {
                  title: "Dreams",
                  artist: "Fleetwood Mac",
                  album: "Rumours",
                  year: 1977,
                  genre: "Rock",
                  duration: 250,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 44123456,
                  albumArt: "https://images.unsplash.com/photo-1484755560615-a4c64e778a6c?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:00.00] Now here you go again\n[00:04.20] You say you want your freedom\n[00:08.40] Well who am I to keep you down?\n[00:12.60] It's only right that you should play the way you feel it\n[00:16.80] But listen carefully to the sound\n[00:21.00] Of your loneliness\n[00:25.20] Like a heartbeat drives you mad\n[00:29.40] In the stillness of remembering what you had\n[00:33.60] And what you lost`,
                  plainLyrics: `Now here you go again\nYou say you want your freedom\nWell who am I to keep you down?\nIt's only right that you should play the way you feel it\nBut listen carefully to the sound\nOf your loneliness\nLike a heartbeat drives you mad\nIn the stillness of remembering what you had\nAnd what you lost`,
                  lyrics: `[00:00.00] Now here you go again\n[00:04.20] You say you want your freedom\n[00:08.40] Well who am I to keep you down?`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
            ],
          },
        ],
      },
      {
        id: "artist-6",
        name: "Nirvana",
        type: "folder",
        path: `${SOURCE_ROOT}/Nirvana`,
        parentId: "root",
        children: [
          {
            id: "album-7",
            name: "Nevermind",
            type: "folder",
            path: `${SOURCE_ROOT}/Nirvana/Nevermind`,
            parentId: "artist-6",
            children: [
              {
                id: "track-nv1",
                name: "Smells Like Teen Spirit.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Nirvana/Nevermind/Smells Like Teen Spirit.flac`,
                parentId: "album-7",
                metadata: {
                  title: "Smells Like Teen Spirit",
                  artist: "Nirvana",
                  album: "Nevermind",
                  year: 1991,
                  genre: "Grunge",
                  duration: 301,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 53123456,
                  albumArt: "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop",
                  plainLyrics: `Load up on guns, bring your friends\nIt's fun to lose and to pretend\nShe's over-bored and self-assured\nOh no, I know a dirty word\n\nHello, hello, hello, how low\nHello, hello, hello, how low\nHello, hello, hello, how low\nHello, hello, hello\n\nWith the lights out, it's less dangerous\nHere we are now, entertain us\nI feel stupid and contagious\nHere we are now, entertain us`,
                  lyrics: `Load up on guns, bring your friends\nIt's fun to lose and to pretend\nShe's over-bored and self-assured\nOh no, I know a dirty word\n\nWith the lights out, it's less dangerous\nHere we are now, entertain us\nI feel stupid and contagious\nHere we are now, entertain us`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: false,
                  hasPlainLyrics: true,
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-nv2",
                name: "Come As You Are.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/Nirvana/Nevermind/Come As You Are.flac`,
                parentId: "album-7",
                metadata: {
                  title: "Come As You Are",
                  artist: "Nirvana",
                  album: "Nevermind",
                  year: 1991,
                  genre: "Grunge",
                  duration: 219,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 38678901,
                  albumArt: "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:00.00] Come as you are, as you were\n[00:04.50] As I want you to be\n[00:09.00] As a friend, as a friend\n[00:13.50] As an old enemy\n[00:18.00] Take your time, hurry up\n[00:22.50] Choice is yours, don't be late\n[00:27.00] Take your time, hurry up\n[00:31.50] The choice is yours, don't be late`,
                  plainLyrics: `Come as you are, as you were\nAs I want you to be\nAs a friend, as a friend\nAs an old enemy\nTake your time, hurry up\nChoice is yours, don't be late`,
                  lyrics: `[00:00.00] Come as you are, as you were\n[00:04.50] As I want you to be\n[00:09.00] As a friend, as a friend`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: false },
                },
              },
            ],
          },
        ],
      },
      {
        id: "artist-7",
        name: "David Bowie",
        type: "folder",
        path: `${SOURCE_ROOT}/David Bowie`,
        parentId: "root",
        children: [
          {
            id: "album-8",
            name: "The Rise and Fall of Ziggy Stardust",
            type: "folder",
            path: `${SOURCE_ROOT}/David Bowie/The Rise and Fall of Ziggy Stardust`,
            parentId: "artist-7",
            children: [
              {
                id: "track-db1",
                name: "Starman.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/David Bowie/The Rise and Fall of Ziggy Stardust/Starman.flac`,
                parentId: "album-8",
                metadata: {
                  title: "Starman",
                  artist: "David Bowie",
                  album: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
                  year: 1972,
                  genre: "Rock",
                  duration: 256,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 45123456,
                  albumArt: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:16.00] Didn't know what time it was\n[00:20.10] The lights were low, oh\n[00:23.80] I leaned back on my radio\n[00:27.50] Some cat was laying down some rock 'n' roll\n[00:31.20] "Lotta soul," he said\n[00:38.90] \n[00:40.20] There's a starman waiting in the sky\n[00:44.00] He'd like to come and meet us\n[00:47.70] But he thinks he'd blow our minds\n[00:51.40] There's a starman waiting in the sky\n[00:55.20] He's told us not to blow it\n[00:58.90] 'Cause he knows it's all worthwhile`,
                  plainLyrics: `Didn't know what time it was\nThe lights were low, oh\nI leaned back on my radio\nSome cat was laying down some rock 'n' roll\n"Lotta soul," he said\n\nThere's a starman waiting in the sky\nHe'd like to come and meet us\nBut he thinks he'd blow our minds\nThere's a starman waiting in the sky\nHe's told us not to blow it\n'Cause he knows it's all worthwhile`,
                  lyrics: `[00:16.00] Didn't know what time it was\n[00:20.10] The lights were low, oh\n[00:23.80] I leaned back on my radio\n[00:27.50] Some cat was laying down some rock 'n' roll`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "complete",
                  sources: { musicbrainz: true, lastfm: true, spotify: true, genius: true },
                },
              },
              {
                id: "track-db2",
                name: "Suffragette City.flac",
                type: "audio",
                path: `${SOURCE_ROOT}/David Bowie/The Rise and Fall of Ziggy Stardust/Suffragette City.flac`,
                parentId: "album-8",
                metadata: {
                  title: "Suffragette City",
                  artist: "David Bowie",
                  album: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
                  year: 1972,
                  genre: "Rock",
                  duration: 201,
                  bitrate: 1411,
                  sampleRate: 44100,
                  format: "FLAC",
                  fileSize: 35456789,
                  albumArt: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop",
                  syncedLyrics: `[00:00.00] Hey man, oh leave me alone you know\n[00:04.50] Hey man, oh Henry, get off the phone, I gotta\n[00:09.00] Hey man, I gotta straighten my face\n[00:13.50] This mellow thighed chick just put my spine out of place\n[00:18.00] Hey man, my work's down the drain\n[00:22.50] Hey man, well she's a total blam-blam\n[00:27.00] Wham bam thank you ma'am`,
                  plainLyrics: `Hey man, oh leave me alone you know\nHey man, oh Henry, get off the phone, I gotta\nHey man, I gotta straighten my face\nThis mellow thighed chick just put my spine out of place\nHey man, my work's down the drain\nHey man, well she's a total blam-blam\nWham bam thank you ma'am`,
                  lyrics: `[00:00.00] Hey man, oh leave me alone you know\n[00:04.50] Hey man, oh Henry, get off the phone, I gotta\n[00:09.00] Hey man, I gotta straighten my face`,
                  lyricsStatus: "Fetched" as const,
                  hasSyncedLyrics: true,
                  hasPlainLyrics: true,
                  enrichmentStatus: "processing",
                  sources: { musicbrainz: true, lastfm: true, spotify: false, genius: false },
                },
              },
            ],
          },
        ],
      },
      {
        id: "unsorted",
        name: "Unsorted",
        type: "folder",
        path: `${SOURCE_ROOT}/Unsorted`,
        parentId: "root",
        children: [
          {
            id: "track-12",
            name: "unknown_track_001.mp3",
            type: "audio",
            path: `${SOURCE_ROOT}/Unsorted/unknown_track_001.mp3`,
            parentId: "unsorted",
            metadata: {
              title: "Unknown Track",
              artist: "Unknown Artist",
              album: "Unknown Album",
              year: 0,
              genre: "Unknown",
              duration: 234,
              bitrate: 192,
              sampleRate: 44100,
              format: "MP3",
              fileSize: 5623456,
              lyricsStatus: "NotFound" as const,
              hasSyncedLyrics: false,
              hasPlainLyrics: false,
              enrichmentStatus: "pending",
              sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
            },
          },
          {
            id: "track-13",
            name: "mystery_song.wav",
            type: "audio",
            path: `${SOURCE_ROOT}/Unsorted/mystery_song.wav`,
            parentId: "unsorted",
            metadata: {
              title: "Mystery Song",
              artist: "Unknown",
              album: "Unknown",
              year: 0,
              genre: "Unknown",
              duration: 198,
              bitrate: 1411,
              sampleRate: 44100,
              format: "WAV",
              fileSize: 34891234,
              lyricsStatus: "NotFound" as const,
              hasSyncedLyrics: false,
              hasPlainLyrics: false,
              enrichmentStatus: "processing",
              sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
            },
          },
        ],
      },
    ],
  },
]

export const mockImportJob: ImportJob = {
  id: "job-1",
  sourcePath: "/Volumes/music",
  destinationPath: "/Music Library",
  status: "running",
  startedAt: new Date(Date.now() - 1000 * 60 * 45), // 45 mins ago
  tracksDiscovered: 847,
  tracksProcessed: 623,
  tracksCopied: 589,
  tracksReview: 18,
  tracksFailed: 16,
}

export const mockTracksForReview: TrackImport[] = [
  {
    id: "review-1",
    originalPath: "/Volumes/External/Music Import/Unknown/track01.mp3",
    status: "review",
    metadata: {
      title: "Track 01",
      artist: "Unknown Artist",
      album: "Unknown Album",
      year: 0,
      genre: "Unknown",
      duration: 234,
      bitrate: 320,
      sampleRate: 44100,
      format: "MP3",
      fileSize: 9345678,
      enrichmentStatus: "complete",
      sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
    },
    suggestedMetadata: {
      title: "Bohemian Rhapsody",
      artist: "Queen",
      album: "A Night at the Opera",
      year: 1975,
      genre: "Rock",
      albumArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    },
    issues: ["Low confidence match (67%)", "Multiple potential matches found"],
    fingerprint: "AQADtNIyRZIkSZEkJXmO44iS5DiO",
  },
  {
    id: "review-2",
    originalPath: "/Volumes/External/Music Import/Downloads/song.flac",
    status: "review",
    metadata: {
      title: "song",
      artist: "Unknown",
      album: "Unknown",
      year: 0,
      genre: "Unknown",
      duration: 312,
      bitrate: 1411,
      sampleRate: 44100,
      format: "FLAC",
      fileSize: 55123456,
      enrichmentStatus: "complete",
      sources: { musicbrainz: true, lastfm: false, spotify: false, genius: false },
    },
    suggestedMetadata: {
      title: "Stairway to Heaven",
      artist: "Led Zeppelin",
      album: "Led Zeppelin IV",
      year: 1971,
      genre: "Rock",
      albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    },
    issues: ["Metadata mismatch with filename"],
    fingerprint: "BQBDtNIyRZIkSZEkJXmO44iS5DiO",
  },
  {
    id: "review-3",
    originalPath: "/Volumes/External/Music Import/CDs/Disc1/03.wav",
    status: "review",
    metadata: {
      title: "03",
      artist: "Unknown",
      album: "Disc1",
      year: 0,
      genre: "Unknown",
      duration: 267,
      bitrate: 1411,
      sampleRate: 44100,
      format: "WAV",
      fileSize: 47123456,
      enrichmentStatus: "complete",
      sources: { musicbrainz: true, lastfm: true, spotify: false, genius: false },
    },
    suggestedMetadata: {
      title: "Hotel California",
      artist: "Eagles",
      album: "Hotel California",
      year: 1977,
      genre: "Rock",
      albumArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
    },
    issues: ["No embedded metadata", "Confidence: 89%"],
    fingerprint: "CQCDtNIyRZIkSZEkJXmO44iS5DiO",
  },
  {
    id: "review-4",
    originalPath: "/Volumes/External/Music Import/Rips/album/track_04.flac",
    status: "review",
    metadata: {
      title: "Track 4",
      artist: "Various Artists",
      album: "Compilation",
      year: 2020,
      genre: "Pop",
      duration: 198,
      bitrate: 1411,
      sampleRate: 44100,
      format: "FLAC",
      fileSize: 35000000,
      enrichmentStatus: "complete",
      sources: { musicbrainz: false, lastfm: false, spotify: true, genius: false },
    },
    suggestedMetadata: {
      title: "Billie Jean",
      artist: "Michael Jackson",
      album: "Thriller",
      year: 1982,
      genre: "Pop",
      albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
    },
    issues: ["Existing metadata conflicts with fingerprint match"],
    fingerprint: "DQDDtNIyRZIkSZEkJXmO44iS5DiO",
  },
  {
    id: "review-5",
    originalPath: "/Volumes/External/Music Import/New/untitled.mp3",
    status: "review",
    metadata: {
      title: "Untitled",
      artist: "",
      album: "",
      year: 0,
      genre: "Unknown",
      duration: 245,
      bitrate: 256,
      sampleRate: 44100,
      format: "MP3",
      fileSize: 7800000,
      enrichmentStatus: "failed",
      sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
    },
    issues: ["No fingerprint match found", "Manual entry required"],
    fingerprint: undefined,
  },
  {
    id: "review-6",
    originalPath: "/Volumes/External/Music Import/Archive/old_recording.wav",
    status: "review",
    metadata: {
      title: "Old Recording",
      artist: "Home Recording",
      album: "Personal",
      year: 1995,
      genre: "Unknown",
      duration: 356,
      bitrate: 1411,
      sampleRate: 44100,
      format: "WAV",
      fileSize: 62000000,
      enrichmentStatus: "complete",
      sources: { musicbrainz: false, lastfm: false, spotify: false, genius: false },
    },
    suggestedMetadata: {
      title: "Wish You Were Here",
      artist: "Pink Floyd",
      album: "Wish You Were Here",
      year: 1975,
      genre: "Progressive Rock",
      albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    },
    issues: ["Low audio quality detected", "Possible live recording"],
    fingerprint: "EQEDtNIyRZIkSZEkJXmO44iS5DiO",
  },
]

export const mockRecentActivity = [
  { id: "act-1", type: "discovered" as const, track: "Come Together.flac", artist: "The Beatles", time: "2 min ago" },
  { id: "act-2", type: "copied" as const, track: "Something.flac", artist: "The Beatles", time: "3 min ago" },
  { id: "act-3", type: "enriched" as const, track: "Dreams.flac", artist: "Fleetwood Mac", time: "4 min ago" },
  { id: "act-4", type: "review" as const, track: "unknown_track.mp3", artist: "Unknown", time: "6 min ago" },
  { id: "act-5", type: "copied" as const, track: "Time.flac", artist: "Pink Floyd", time: "8 min ago" },
  { id: "act-6", type: "failed" as const, track: "corrupted_file.mp3", artist: "Unknown", time: "10 min ago" },
  { id: "act-7", type: "discovered" as const, track: "Smells Like Teen Spirit.flac", artist: "Nirvana", time: "12 min ago" },
  { id: "act-8", type: "enriched" as const, track: "Get Lucky.flac", artist: "Daft Punk", time: "15 min ago" },
]

// Artists in library
export const mockArtists: Artist[] = [
  {
    id: "artist-beatles",
    name: "The Beatles",
    image: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
    genres: ["Rock", "Pop"],
    albumsInLibrary: 3,
    totalAlbums: 13,
    tracksInLibrary: 6,
    totalTracks: 213,
  },
  {
    id: "artist-pinkfloyd",
    name: "Pink Floyd",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    genres: ["Progressive Rock", "Psychedelic Rock"],
    albumsInLibrary: 1,
    totalAlbums: 15,
    tracksInLibrary: 4,
    totalTracks: 165,
  },
  {
    id: "artist-daftpunk",
    name: "Daft Punk",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
    genres: ["Electronic", "House"],
    albumsInLibrary: 1,
    totalAlbums: 4,
    tracksInLibrary: 2,
    totalTracks: 52,
  },
  {
    id: "artist-radiohead",
    name: "Radiohead",
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
    genres: ["Alternative Rock", "Art Rock"],
    albumsInLibrary: 1,
    totalAlbums: 9,
    tracksInLibrary: 2,
    totalTracks: 101,
  },
  {
    id: "artist-fleetwoodmac",
    name: "Fleetwood Mac",
    image: "https://images.unsplash.com/photo-1484755560615-a4c64e778a6c?w=400&h=400&fit=crop",
    genres: ["Rock", "Soft Rock"],
    albumsInLibrary: 1,
    totalAlbums: 18,
    tracksInLibrary: 2,
    totalTracks: 142,
  },
  {
    id: "artist-nirvana",
    name: "Nirvana",
    image: "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop",
    genres: ["Grunge", "Alternative Rock"],
    albumsInLibrary: 1,
    totalAlbums: 3,
    tracksInLibrary: 2,
    totalTracks: 49,
  },
  {
    id: "artist-davidbowie",
    name: "David Bowie",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop",
    genres: ["Rock", "Art Rock", "Glam Rock"],
    albumsInLibrary: 1,
    totalAlbums: 26,
    tracksInLibrary: 2,
    totalTracks: 287,
  },
]

// Full discography for The Beatles
export const mockBeatlesDiscography: DiscographyAlbum[] = [
  {
    id: "disc-abbey",
    name: "Abbey Road",
    year: 1969,
    albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop",
    type: "album",
    inLibrary: true,
    tracksOwned: 3,
    totalTracks: 17,
    tracks: [
      { id: "t1", name: "Come Together", trackNumber: 1, duration: 259, inLibrary: true, downloadStatus: "downloaded" },
      { id: "t2", name: "Something", trackNumber: 2, duration: 182, inLibrary: true, downloadStatus: "downloaded" },
      { id: "t3", name: "Maxwell's Silver Hammer", trackNumber: 3, duration: 207, inLibrary: false, downloadStatus: "available" },
      { id: "t4", name: "Oh! Darling", trackNumber: 4, duration: 206, inLibrary: false, downloadStatus: "available" },
      { id: "t5", name: "Octopus's Garden", trackNumber: 5, duration: 171, inLibrary: false, downloadStatus: "available" },
      { id: "t6", name: "I Want You (She's So Heavy)", trackNumber: 6, duration: 467, inLibrary: false, downloadStatus: "available" },
      { id: "t7", name: "Here Comes The Sun", trackNumber: 7, duration: 185, inLibrary: true, downloadStatus: "downloaded" },
      { id: "t8", name: "Because", trackNumber: 8, duration: 165, inLibrary: false, downloadStatus: "available" },
      { id: "t9", name: "You Never Give Me Your Money", trackNumber: 9, duration: 242, inLibrary: false, downloadStatus: "available" },
      { id: "t10", name: "Sun King", trackNumber: 10, duration: 146, inLibrary: false, downloadStatus: "available" },
      { id: "t11", name: "Mean Mr. Mustard", trackNumber: 11, duration: 66, inLibrary: false, downloadStatus: "available" },
      { id: "t12", name: "Polythene Pam", trackNumber: 12, duration: 72, inLibrary: false, downloadStatus: "available" },
      { id: "t13", name: "She Came In Through the Bathroom Window", trackNumber: 13, duration: 118, inLibrary: false, downloadStatus: "available" },
      { id: "t14", name: "Golden Slumbers", trackNumber: 14, duration: 91, inLibrary: false, downloadStatus: "available" },
      { id: "t15", name: "Carry That Weight", trackNumber: 15, duration: 97, inLibrary: false, downloadStatus: "available" },
      { id: "t16", name: "The End", trackNumber: 16, duration: 140, inLibrary: false, downloadStatus: "available" },
      { id: "t17", name: "Her Majesty", trackNumber: 17, duration: 23, inLibrary: false, downloadStatus: "available" },
    ],
  },
  {
    id: "disc-letitbe",
    name: "Let It Be",
    year: 1970,
    albumArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    type: "album",
    inLibrary: true,
    tracksOwned: 1,
    totalTracks: 12,
    tracks: [
      { id: "t18", name: "Two of Us", trackNumber: 1, duration: 214, inLibrary: false, downloadStatus: "available" },
      { id: "t19", name: "Dig a Pony", trackNumber: 2, duration: 235, inLibrary: false, downloadStatus: "available" },
      { id: "t20", name: "Across the Universe", trackNumber: 3, duration: 228, inLibrary: false, downloadStatus: "available" },
      { id: "t21", name: "I Me Mine", trackNumber: 4, duration: 136, inLibrary: false, downloadStatus: "available" },
      { id: "t22", name: "Dig It", trackNumber: 5, duration: 51, inLibrary: false, downloadStatus: "available" },
      { id: "t23", name: "Let It Be", trackNumber: 6, duration: 243, inLibrary: true, downloadStatus: "downloaded" },
      { id: "t24", name: "Maggie Mae", trackNumber: 7, duration: 40, inLibrary: false, downloadStatus: "available" },
      { id: "t25", name: "I've Got a Feeling", trackNumber: 8, duration: 217, inLibrary: false, downloadStatus: "available" },
      { id: "t26", name: "One After 909", trackNumber: 9, duration: 170, inLibrary: false, downloadStatus: "available" },
      { id: "t27", name: "The Long and Winding Road", trackNumber: 10, duration: 222, inLibrary: false, downloadStatus: "available" },
      { id: "t28", name: "For You Blue", trackNumber: 11, duration: 152, inLibrary: false, downloadStatus: "available" },
      { id: "t29", name: "Get Back", trackNumber: 12, duration: 191, inLibrary: false, downloadStatus: "available" },
    ],
  },
  {
    id: "disc-whitea",
    name: "The Beatles (White Album)",
    year: 1968,
    albumArt: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop",
    type: "album",
    inLibrary: false,
    tracksOwned: 0,
    totalTracks: 30,
    tracks: [
      { id: "t30", name: "Back in the U.S.S.R.", trackNumber: 1, duration: 163, inLibrary: false, downloadStatus: "available" },
      { id: "t31", name: "Dear Prudence", trackNumber: 2, duration: 236, inLibrary: false, downloadStatus: "available" },
      { id: "t32", name: "Glass Onion", trackNumber: 3, duration: 132, inLibrary: false, downloadStatus: "available" },
      { id: "t33", name: "Ob-La-Di, Ob-La-Da", trackNumber: 4, duration: 189, inLibrary: false, downloadStatus: "available" },
      { id: "t34", name: "Wild Honey Pie", trackNumber: 5, duration: 54, inLibrary: false, downloadStatus: "available" },
      { id: "t35", name: "The Continuing Story of Bungalow Bill", trackNumber: 6, duration: 191, inLibrary: false, downloadStatus: "available" },
      { id: "t36", name: "While My Guitar Gently Weeps", trackNumber: 7, duration: 284, inLibrary: false, downloadStatus: "available" },
      { id: "t37", name: "Happiness Is a Warm Gun", trackNumber: 8, duration: 163, inLibrary: false, downloadStatus: "available" },
      { id: "t38", name: "Martha My Dear", trackNumber: 9, duration: 148, inLibrary: false, downloadStatus: "available" },
      { id: "t39", name: "Blackbird", trackNumber: 10, duration: 138, inLibrary: false, downloadStatus: "available" },
    ],
  },
  {
    id: "disc-sgtpepper",
    name: "Sgt. Pepper's Lonely Hearts Club Band",
    year: 1967,
    albumArt: "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop",
    type: "album",
    inLibrary: false,
    tracksOwned: 0,
    totalTracks: 13,
    tracks: [
      { id: "t40", name: "Sgt. Pepper's Lonely Hearts Club Band", trackNumber: 1, duration: 122, inLibrary: false, downloadStatus: "available" },
      { id: "t41", name: "With a Little Help from My Friends", trackNumber: 2, duration: 164, inLibrary: false, downloadStatus: "available" },
      { id: "t42", name: "Lucy in the Sky with Diamonds", trackNumber: 3, duration: 207, inLibrary: false, downloadStatus: "available" },
      { id: "t43", name: "Getting Better", trackNumber: 4, duration: 167, inLibrary: false, downloadStatus: "available" },
      { id: "t44", name: "Fixing a Hole", trackNumber: 5, duration: 156, inLibrary: false, downloadStatus: "available" },
      { id: "t45", name: "She's Leaving Home", trackNumber: 6, duration: 215, inLibrary: false, downloadStatus: "available" },
      { id: "t46", name: "Being for the Benefit of Mr. Kite!", trackNumber: 7, duration: 157, inLibrary: false, downloadStatus: "available" },
      { id: "t47", name: "Within You Without You", trackNumber: 8, duration: 305, inLibrary: false, downloadStatus: "available" },
      { id: "t48", name: "When I'm Sixty-Four", trackNumber: 9, duration: 157, inLibrary: false, downloadStatus: "available" },
      { id: "t49", name: "Lovely Rita", trackNumber: 10, duration: 162, inLibrary: false, downloadStatus: "available" },
      { id: "t50", name: "Good Morning Good Morning", trackNumber: 11, duration: 161, inLibrary: false, downloadStatus: "available" },
      { id: "t51", name: "Sgt. Pepper's Lonely Hearts Club Band (Reprise)", trackNumber: 12, duration: 79, inLibrary: false, downloadStatus: "available" },
      { id: "t52", name: "A Day in the Life", trackNumber: 13, duration: 337, inLibrary: false, downloadStatus: "available" },
    ],
  },
  {
    id: "disc-revolver",
    name: "Revolver",
    year: 1966,
    albumArt: "https://images.unsplash.com/photo-1484755560615-a4c64e778a6c?w=400&h=400&fit=crop",
    type: "album",
    inLibrary: false,
    tracksOwned: 0,
    totalTracks: 14,
    tracks: [
      { id: "t53", name: "Taxman", trackNumber: 1, duration: 159, inLibrary: false, downloadStatus: "available" },
      { id: "t54", name: "Eleanor Rigby", trackNumber: 2, duration: 126, inLibrary: false, downloadStatus: "available" },
      { id: "t55", name: "I'm Only Sleeping", trackNumber: 3, duration: 181, inLibrary: false, downloadStatus: "available" },
      { id: "t56", name: "Love You To", trackNumber: 4, duration: 180, inLibrary: false, downloadStatus: "available" },
      { id: "t57", name: "Here, There and Everywhere", trackNumber: 5, duration: 145, inLibrary: false, downloadStatus: "available" },
      { id: "t58", name: "Yellow Submarine", trackNumber: 6, duration: 159, inLibrary: false, downloadStatus: "available" },
    ],
  },
]

// Spotify playlists and tracks
export const mockSpotifyPlaylists: SpotifyPlaylist[] = [
  {
    id: "sp-liked",
    name: "Liked Songs",
    description: "Your saved tracks",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    trackCount: 847,
    owner: "You",
    syncStatus: "partial",
    tracksMatched: 234,
    lastSynced: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
  {
    id: "sp-discover",
    name: "Discover Weekly",
    description: "Your weekly mixtape of fresh music",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
    trackCount: 30,
    owner: "Spotify",
    syncStatus: "not_synced",
    tracksMatched: 0,
  },
  {
    id: "sp-rock",
    name: "Classic Rock Hits",
    description: "The best of classic rock",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    trackCount: 156,
    owner: "You",
    syncStatus: "synced",
    tracksMatched: 142,
    lastSynced: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: "sp-chill",
    name: "Chill Vibes",
    description: "Relaxing tunes for any mood",
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop",
    trackCount: 89,
    owner: "You",
    syncStatus: "syncing",
    tracksMatched: 45,
  },
  {
    id: "sp-workout",
    name: "Workout Mix",
    description: "High energy tracks",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop",
    trackCount: 67,
    owner: "You",
    syncStatus: "not_synced",
    tracksMatched: 0,
  },
]

export const mockSpotifyLikedSongs: SpotifyTrack[] = [
  { id: "spt-1", name: "Come Together", artist: "The Beatles", album: "Abbey Road", albumArt: "https://images.unsplash.com/photo-1619983081563-430f63602796?w=400&h=400&fit=crop", duration: 259, inLibrary: true, matchConfidence: 100 },
  { id: "spt-2", name: "Bohemian Rhapsody", artist: "Queen", album: "A Night at the Opera", albumArt: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop", duration: 354, inLibrary: false, matchConfidence: undefined },
  { id: "spt-3", name: "Time", artist: "Pink Floyd", album: "The Dark Side of the Moon", albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop", duration: 413, inLibrary: true, matchConfidence: 100 },
  { id: "spt-4", name: "Stairway to Heaven", artist: "Led Zeppelin", album: "Led Zeppelin IV", albumArt: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop", duration: 482, inLibrary: false, matchConfidence: undefined },
  { id: "spt-5", name: "Get Lucky", artist: "Daft Punk", album: "Random Access Memories", albumArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop", duration: 369, inLibrary: true, matchConfidence: 100 },
  { id: "spt-6", name: "Hotel California", artist: "Eagles", album: "Hotel California", albumArt: "https://images.unsplash.com/photo-1484755560615-a4c64e778a6c?w=400&h=400&fit=crop", duration: 391, inLibrary: false, matchConfidence: undefined },
  { id: "spt-7", name: "Karma Police", artist: "Radiohead", album: "OK Computer", albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop", duration: 264, inLibrary: true, matchConfidence: 100 },
  { id: "spt-8", name: "Wish You Were Here", artist: "Pink Floyd", album: "Wish You Were Here", albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop", duration: 307, inLibrary: false, matchConfidence: undefined },
  { id: "spt-9", name: "Paranoid Android", artist: "Radiohead", album: "OK Computer", albumArt: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&h=400&fit=crop", duration: 386, inLibrary: true, matchConfidence: 100 },
  { id: "spt-10", name: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", albumArt: "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop", duration: 301, inLibrary: false, matchConfidence: undefined },
  { id: "spt-11", name: "Money", artist: "Pink Floyd", album: "The Dark Side of the Moon", albumArt: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop", duration: 382, inLibrary: true, matchConfidence: 100 },
  { id: "spt-12", name: "Sweet Child O' Mine", artist: "Guns N' Roses", album: "Appetite for Destruction", albumArt: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=400&fit=crop", duration: 356, inLibrary: false, matchConfidence: undefined },
  { id: "spt-13", name: "Dreams", artist: "Fleetwood Mac", album: "Rumours", albumArt: "https://images.unsplash.com/photo-1484755560615-a4c64e778a6c?w=400&h=400&fit=crop", duration: 250, inLibrary: true, matchConfidence: 100 },
  { id: "spt-14", name: "Smells Like Teen Spirit", artist: "Nirvana", album: "Nevermind", albumArt: "https://images.unsplash.com/photo-1471478331149-c72f17e33c73?w=400&h=400&fit=crop", duration: 301, inLibrary: true, matchConfidence: 100 },
  { id: "spt-15", name: "Starman", artist: "David Bowie", album: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", albumArt: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop", duration: 256, inLibrary: true, matchConfidence: 100 },
]

export function findFileById(files: FileItem[], id: string): FileItem | null {
  for (const file of files) {
    if (file.id === id) return file
    if (file.children) {
      const found = findFileById(file.children, id)
      if (found) return found
    }
  }
  return null
}

export function getPathToFile(files: FileItem[], targetId: string): FileItem[] {
  const path: FileItem[] = []
  
  function search(items: FileItem[], target: string): boolean {
    for (const item of items) {
      if (item.id === target) {
        path.push(item)
        return true
      }
      if (item.children && search(item.children, target)) {
        path.unshift(item)
        return true
      }
    }
    return false
  }
  
  search(files, targetId)
  return path
}
